[9.0][MIG] portal_claim: merged in crm_claim
OCA/OpenUpgrade pull request #1021
Opened 2017-08-14 14:15 UTC by cubells

Features are merged in crm_claim module

2017-08-15 11:20 UTC, pedrobaeza requested changes

2017-08-15 11:20 UTC, pedrobaeza commented on openerp/addons/base/migrations/9.0.1.3/pre-migration.py
> +            ('portal_claim', 'crm_claim'),
Looking at the code at 8.0 and 9.0, it's better to just rename (in apriori.py) `portal_claim` to `website_crm_claim`

2017-08-16 08:48 UTC, MiquelRForgeFlow requested changes

2017-08-16 08:48 UTC, mreficent commented on addons/crm_claim/migrations/9.0.1.0/pre-migration.py
> +        env.ref('portal_claim.portal_claim_rule').unlink()
Delete this else

2017-08-16 08:50 UTC, mreficent commented
And please, update documentation

2017-08-16 09:11 UTC, pedrobaeza commented on addons/crm_claim/migrations/9.0.1.0/pre-migration.py
> +    # Portal_claim is merged here and It is needed rename xml-id
This is not needed anymore making the renaming in the other place. Please restore it as it was.

2017-08-16 09:18 UTC, pedrobaeza commented on addons/crm_claim/migrations/9.0.1.0/pre-migration.py
> +    if openupgrade.is_module_installed(env.cr, 'website_crm_claim'):
I'm talking about leaving this as it was before this PR. You don't need to do this with the renaming of the module.

2017-08-16 09:19 UTC, mreficent commented on addons/crm_claim/migrations/9.0.1.0/pre-migration.py
> +    if openupgrade.is_module_installed(env.cr, 'website_crm_claim'):
True :+1:

2017-08-16 10:38 UTC, pedrobaeza commented on addons/crm_claim/migrations/9.0.1.0/pre-migration.py
> +@openupgrade.migrate(use_env=True)
You're still modifying this script. Please restore it as it was for making the diff smaller.

2017-08-16 10:46 UTC, cubells commented
You are right @pedrobaeza 

Sorry.

2017-08-16 10:54 UTC, pedrobaeza commented
Agh, I miss to say you about the documentation... Please put `Done - Renamed to website_crm_claim`

2017-08-16 10:56 UTC, pedrobaeza commented
And you have to fill also `website_crm_claim` line with `Done - Renamed from portal_claim`

2017-08-16 11:57 UTC, MiquelRForgeFlow approved these changes

2017-08-16 14:14 UTC, pedrobaeza approved these changes

2017-08-16 14:14 UTC, merged