[9.0][IMP] *: Use new rename_fields method
OCA/OpenUpgrade pull request #1159
Opened 2017-11-05 11:04 UTC by pedrobaeza

This is a huge change, but it's only the result of applying 2 techniques:

* Use `rename_fields` with the existing renamed columns that are actually fields.
* Use `rename_fields` with the fields that have been handled by Odoo with `oldname` attribute (thanks @StefanRijnhart for including that lines in the analysis!)

With this, we improve even more our migration, handling:

* Fields that have been renamed and are translatable. The translations were missing before, so it can be considered this even a bug.
* If the fields are included in an export profile (first level for now), they are automatically handled.
* If the fields are included in a filter as domain (first level for now) or a group by, they are automatically handled.

2017-11-06 07:14 UTC, StefanRijnhart approved these changes

2017-11-06 07:16 UTC, pedrobaeza commented
We need to remove the commit for changing openupgradelib alternative source before merging.

2017-11-06 09:37 UTC, MiquelRForgeFlow requested changes

2017-11-06 09:37 UTC, mreficent commented on addons/sale/migrations/9.0.1.0/pre-migration.py
> +    ('account.invoice', 'accouwnt_invoice', 'section_id', 'team_id'),
account_invoice

2017-11-06 21:36 UTC, pedrobaeza commented on addons/sale/migrations/9.0.1.0/pre-migration.py
> +    ('account.invoice', 'accouwnt_invoice', 'section_id', 'team_id'),
Good catch! Changed

2017-11-06 21:37 UTC, pedrobaeza commented
@mreficent please merge when CIs finish

2017-11-07 09:37 UTC, MiquelRForgeFlow approved these changes

2017-11-07 09:37 UTC, merged