Migration hr contract
OCA/OpenUpgrade pull request #1180
Opened 2017-11-16 13:29 UTC by fayezqandeel

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2017-11-23 20:53 UTC, pedrobaeza requested changes

2017-11-23 20:53 UTC, pedrobaeza commented on addons/hr_contract/migrations/11.0.1.0/openupgrade_analysis_work.txt
> +hr_contract  / hr.contract              / working_hours (many2one)      : DEL relation: resource.calendar
This is clearly a rename of the field from `working_hours` to `resource_calendar_id`, and more if you check the label from both fields in v10 and v11: `Working Schedule`. Please pay attention to these details.

2017-12-18 12:30 UTC, fayezqandeel commented
@pedrobaeza rename field done on pre_migration.py

2018-04-07 12:10 UTC, pedrobaeza commented
Completed the migration with:

* Fill company in contract from job.
* Remove deleted noupdate records.

2018-04-07 12:10 UTC, pedrobaeza approved these changes

2018-04-07 12:33 UTC, pedrobaeza commented
The unlink of the filter has revealed a possible problem with renamed_models method in OpenUpgrade. I'll investigate this further.

2018-04-08 13:13 UTC, pedrobaeza commented
This depends indirectly of `base_automation`. We will probably need to add the dependency in the manifest for avoiding problems in the loading order (as we are unlinking base.automation records that are not anymore in this version, nor the dependency).

2018-04-08 13:15 UTC, pedrobaeza commented
I just think about other better solution. Do the unlinking on end-migration where all the models are already loaded.

2018-04-10 22:06 UTC, pedrobaeza commented
Correct after merging base_automation, so I merge.

2018-04-10 22:06 UTC, merged