[FIX] don't choke on deleted stages
OCA/OpenUpgrade pull request #1217
Opened 2017-12-07 15:38 UTC by hbrunn

stages are noupdate: https://github.com/OCA/OpenUpgrade/blob/9.0/addons/crm/data/crm_stage_data.xml

2017-12-07 16:00 UTC, pedrobaeza approved these changes

2017-12-07 18:56 UTC, pedrobaeza commented
There's an strange error in Travis...

2017-12-12 15:37 UTC, pedrobaeza requested changes
This seems either the XML file is not correct or the code in openupgradelib for handling `init_no_create` mode is not correct.

2018-01-11 13:41 UTC, hbrunn commented
@pedrobaeza fixed, I passed the parameter wrongly, shame!

2018-01-12 02:10 UTC, pedrobaeza approved these changes

2018-01-12 02:10 UTC, merged