Improve reconcile_ref creation.
OCA/OpenUpgrade pull request #1269
Opened 2018-02-06 12:12 UTC by hmartinet

Create and set values for reconcile_ref field of account_move_line
to bypass ORM auto update (memory usage and speed improvement for
large account_move_line).

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2018-02-06 21:33 UTC, hmartinet commented
@StefanRijnhart This will solve my problem with 1'000'000 records in account_move_line. The migration from 7.0 to 8.0 was successful and complete on a 8Go RAM instance. I have to write similar statements for 9.0 and 10.0 migration (I have same problem in 9.0, now I use a monitoring tool to check memory usage graph during the process)

2018-02-06 23:52 UTC, legalsylvain approved these changes
hi Thanks a lot.
It seems replace correctly the computed function.
https://github.com/OCA/OCB/blob/8.0/addons/account/account_move_line.py#L445

maybe one minor approvment : switch between the two updates

LGTM otherwise. 
```
    cr.execute("""
        update account_move_line ml
            set reconcile_ref = r.name
        from account_move_reconcile r
        where ml.reconcile_id = r.id;
        """)


    cr.execute("""
        update account_move_line ml
            set reconcile_ref = r.name
        from account_move_reconcile r
        where ml.reconcile_partial_id = r.id
        and ml.reconcile_ref is null
        """)
```

2018-02-07 07:58 UTC, pedrobaeza requested changes
A little refactoring for better reading: please enclose all the code in a method that is called from the main method (`migrate`), and the initial comment can be method doc.

2018-02-07 08:57 UTC, hmartinet commented
@legalsylvain I think this order is the right one. A line should never be partially AND fully reconciled (it would be a data inconsistency but it's not the point here to fix that). But if that is still the case we want to keep the full reconcile name, then we update the full after the partial to guarantee that.

@pedrobaeza Ok I will fix it

2018-02-07 09:05 UTC, legalsylvain commented
Hi @hmartinet. I wrote **and ml.reconcile_ref is null** in the second statement, so IMO the two proposals make the same things and I guess that the second update will be executed faster. But not a big deal.
regards.

2018-02-07 09:10 UTC, pedrobaeza commented on addons/account/migrations/8.0.1.1/pre-migration.py
> +
Please don't add these extra lines. PEP8 advises not to abuse of these lines and in this case, it doesn't add any extra value.

2018-02-07 09:13 UTC, hmartinet commented
@legalsylvain Ok I understand your point of view. But I still think that my proposal is more logical (functionally). And yes it's a philosophical choice that does not really matter.

2018-02-07 22:03 UTC, pedrobaeza approved these changes

2018-02-07 22:04 UTC, merged

2018-02-07 22:05 UTC, pedrobaeza commented
Thank you for your contribution.

2018-02-08 09:05 UTC, StefanRijnhart commented
Coming late to the party, but thanks for following this up!

2018-02-08 16:26 UTC, hmartinet commented
@StefanRijnhart :wink: