[MIG][11.0] payment_paypal: migration scripts
OCA/OpenUpgrade pull request #1323
Opened 2018-04-30 16:16 UTC by cubells

cc @Tecnativa

2018-05-01 12:49 UTC, pedrobaeza requested changes

2018-05-01 12:49 UTC, pedrobaeza commented on addons/payment_paypal/migrations/11.0.1.0/noupdate_changes.xml
> +    <field name="view_template_id" ref="paypal_acquirer_button"/>
This is not correct, as this one is the old v10 value. I think you have run the script with the reversed arguments. This should be `paypal_form`.

2018-05-01 12:49 UTC, pedrobaeza commented on addons/payment_paypal/migrations/11.0.1.0/noupdate_changes.xml
> +    <field name="paypal_pdt_token"/>
This one is incorrect as well. It should be `dummy`.

2018-05-07 07:49 UTC, cubells commented
@pedrobaeza done

2018-05-09 16:31 UTC, MiquelRForgeFlow approved these changes

2018-05-09 16:34 UTC, pedrobaeza approved these changes

2018-05-09 16:34 UTC, merged