[REN] membership_prorrate to membership_prorate
OCA/OpenUpgrade pull request #1341
Opened 2018-05-16 16:22 UTC by chienandalu

Depends on:

- [ ] https://github.com/OCA/vertical-association/pull/41 membership_prorate migration to 11.0

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2018-05-16 18:08 UTC, pedrobaeza requested changes

2018-05-16 18:08 UTC, pedrobaeza commented on odoo/addons/openupgrade_records/lib/apriori.py
> +    'membership_prorrate': 'membership_prorate',
This should be on `renamed_modules` variable

2018-05-17 07:27 UTC, chienandalu commented
Of course... done!

2018-05-17 07:56 UTC, StefanRijnhart approved these changes
Thanks!

2018-05-17 07:56 UTC, merged