[MIG][11.0] website_membership: nothing to do
OCA/OpenUpgrade pull request #1346
Opened 2018-05-17 10:46 UTC by cubells

cc @Tecnativa

2018-05-17 18:37 UTC, pedrobaeza requested changes

2018-05-17 18:37 UTC, pedrobaeza commented on odoo/openupgrade/doc/source/modules100-110.rst
> +|website_membership                 | Nothing to do                                    |
The table is incorrect (one space more).

2018-05-24 09:23 UTC, cubells commented
@pedrobaeza 
done!

2018-06-01 09:37 UTC, pedrobaeza approved these changes

2018-06-01 09:38 UTC, pedrobaeza commented
Please make `membership` migration

2018-06-05 09:21 UTC, cubells commented
@pedrobaeza 

done: https://github.com/OCA/OpenUpgrade/pull/1364

2018-06-05 13:21 UTC, merged