[MIG][11.0] website_sale_delivery: migration scripts
OCA/OpenUpgrade pull request #1358
Opened 2018-05-30 15:32 UTC by cubells

Depends on:

- [x] delivery - #1103

cc @Tecnativa

2018-05-30 17:49 UTC, pedrobaeza requested changes

2018-05-30 17:49 UTC, pedrobaeza commented on addons/website_sale_delivery/migrations/11.0.1.0/post-migration.py
> +    openupgrade.update_module_moved_fields(
Do this on pre

2018-05-30 20:27 UTC, cubells commented
@pedrobaeza 

done!

2018-05-31 07:13 UTC, pedrobaeza approved these changes

2018-05-31 07:38 UTC, StefanRijnhart approved these changes

2018-06-21 18:20 UTC, pedrobaeza commented
Rebased now that dependencies are merged.

2018-06-21 18:32 UTC, cubells commented
@pedrobaeza done!

2018-06-22 10:58 UTC, pedrobaeza approved these changes

2018-06-22 10:59 UTC, merged