[10.0][FIX]purchase_requisition fill product
OCA/OpenUpgrade pull request #1440
Opened 2018-07-10 16:15 UTC by aheficent

Description of the issue/feature this PR addresses:
Missing mandatory field in purchase requisition post_migration script

Current behavior before PR:
An error raises asking for categ_id field when creating a product

Desired behavior after PR is merged:
No error is raised and the product is created for the purchase_requisition line

Solution: adding a default category. Actual migration run successfully after the fix.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2018-07-10 16:15 UTC, aheficent commented
ping @mreficent

2018-07-11 10:08 UTC, MiquelRForgeFlow approved these changes
LGTM

But it's strange that the default `_get_default_category_id` doesn't execute.

2018-08-02 15:17 UTC, pedrobaeza requested changes
Check the code for the default value:

https://github.com/OCA/OpenUpgrade/blob/e1623b0ca8f8663da5b42529da796af952dbaa83/addons/product/models/product_template.py#L23

What I think is that the category "All" has been changed in your DB from normal to view, and that's the reason why it doesn't work, so the product you are creating is going to be inside a view category. You should find the first category that has `type = 'normal'` when default categ is not of that type.

2018-08-29 06:04 UTC, pedrobaeza commented
Are you going to change this, @aheficent ?

2018-09-03 07:26 UTC, aheficent commented
I am not sure if I understood. Are you proposing this?

1.- check the type of the category.
2.- if the type is view find a type normal and then assign that type.

2018-09-03 07:30 UTC, pedrobaeza commented
Exactly

2018-09-03 07:55 UTC, aheficent commented
Ok, it makes sense. I'll do that

2018-11-30 14:43 UTC, aheficent commented
Closed as solved here: https://github.com/OCA/OpenUpgrade/pull/1637

2018-11-30 14:43 UTC, closed without merging

2018-11-30 14:46 UTC, aheficent commented
BTW please look for existing PRs before opening new ones.