[MIG] website_event_track: Nothing to do
OCA/OpenUpgrade pull request #1720
Opened 2019-02-05 09:44 UTC by cubells

cc @Tecnativa

2019-02-05 13:19 UTC, MiquelRForgeFlow requested changes

2019-02-05 13:19 UTC, mreficent commented on addons/website_event_track/migrations/11.0.1.0/openupgrade_analysis_work.txt
> +# Nothing to do
There exists a map between the `state` and the `stage_id`. Each event track that had an state should have now the corresponding stage_id. There exists a stage_id for each state.

2019-02-05 13:19 UTC, mreficent commented on addons/website_event_track/migrations/11.0.1.0/openupgrade_analysis_work.txt
> +# Nothing to do
if the event track record doesn't have a partner_id, then you should fill it with one of the speaker_ids

2019-06-05 18:30 UTC, mreficent commented
Superseded by https://github.com/OCA/OpenUpgrade/pull/1874.

2019-06-17 22:37 UTC, pedrobaeza commented
Superseeded by #1874

2019-06-17 22:37 UTC, closed without merging