[12.0][MIG] website_hr_recruitment
OCA/OpenUpgrade pull request #1833
Opened 2019-05-16 11:33 UTC by mreficent

Migration scripts for `website_hr_recruitment` module.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2019-06-16 01:19 UTC, pedrobaeza requested changes
You have to convert BS3 > BS4 content in `hr.job`.`website_description`

2019-06-16 01:20 UTC, pedrobaeza commented
And please use convention for naming pre-migration scripts.

2019-06-17 08:48 UTC, mreficent commented
done

2019-06-17 18:35 UTC, pedrobaeza approved these changes

2019-06-17 18:35 UTC, merged