[12.0][FIX] account_voucher: assure company_id in old databases
OCA/OpenUpgrade pull request #1851
Opened 2019-05-24 16:36 UTC by mreficent

In odoo v8, the company_id was stored. Thus, maybe some databases
that have been migrating since v8, may still have that column. Thus,
if new records have been created in newer versions, they may have
this field empty.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2019-06-16 00:34 UTC, pedrobaeza requested changes

2019-06-16 00:34 UTC, pedrobaeza commented on addons/account_voucher/migrations/12.0.1.0/pre-lol.py
> +        """
Add here `AND av.company_id IS NULL`

2019-06-17 08:32 UTC, mreficent commented on addons/account_voucher/migrations/12.0.1.0/pre-lol.py
> +        """
done

2019-06-17 18:37 UTC, pedrobaeza approved these changes

2019-06-17 18:37 UTC, merged