[12.0][account] try to link moves with their reversals
OCA/OpenUpgrade pull request #1860
Opened 2019-05-29 07:22 UTC by jbeficent

Even if you have account_reversal installed, it may well be that there are old reversals that were created without this module. This PR will try to link all moves with their corresponding reversals, excluding those that were created using module 'account_reversal'.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2019-05-30 08:24 UTC, MiquelRForgeFlow requested changes
This fix has no sense. There is no `for`. Only there is an `if` and an `else`.

2019-05-30 08:44 UTC, jbeficent commented
@mreficent the if checks wether you habe the account_reversal module installed. But if you have it installed, and you have prior reversals made without this module, then the old reversals will not be fixed.

This PR fixes that, and I checked that it solves the issue it describes.

2019-05-30 08:57 UTC, MiquelRForgeFlow requested changes

2019-05-30 08:57 UTC, mreficent commented on addons/account/migrations/12.0.1.1/post-migration.py
> +                and m not in moves_linked_to_reversals)
here `moves_linked_to_reversals` will be always empty, so it's irrelevant add `m not in moves_linked_to_reversals`

2019-05-30 08:57 UTC, mreficent commented on addons/account/migrations/12.0.1.1/post-migration.py
> +        moves_linked_to_reversals += all_moves.filtered(
and here you are filling `moves_linked_to_reversals` but without any use

2019-05-30 10:22 UTC, mreficent commented
Fixed :+1:

2019-05-30 10:23 UTC, MiquelRForgeFlow approved these changes

2019-05-31 09:13 UTC, pedrobaeza commented
Added improvement for better performance.

2019-05-31 16:45 UTC, MiquelRForgeFlow requested changes

2019-05-31 16:45 UTC, mreficent commented on addons/account/migrations/12.0.1.1/post-migration.py
> +            ('reverse_entry_id', '!=', False),
'reverse_entry_id', **'='**, False

2019-05-31 17:24 UTC, pedrobaeza approved these changes

2019-06-03 09:49 UTC, mreficent commented
I just fixed flake8

2019-06-03 09:50 UTC, MiquelRForgeFlow approved these changes

2019-06-03 09:50 UTC, merged