[13.0][MIG] hr_payroll: Move to OCA payroll
OCA/OpenUpgrade pull request #2988
Opened 2021-11-29 14:06 UTC by victoralmau

Move to OCA payroll

Please @pedrobaeza can you review it?

@Tecnativa TT32606

2021-11-29 14:08 UTC, legalsylvain approved these changes

2021-11-29 14:28 UTC, MiquelRForgeFlow requested changes
Should it be in renamed_modules, right?

In addition, where are the migration scripts for this modules? They are not needed?

2021-11-29 14:28 UTC, MiquelRForgeFlow commented on odoo/addons/openupgrade_records/lib/apriori.py
> +    'hr_payroll': 'payroll',
```suggestion
    'hr_payroll': 'payroll',
    'hr_payroll_account': 'payroll_account',
```

2021-11-29 16:27 UTC, pedrobaeza commented on odoo/openupgrade/doc/source/modules120-130.rst
> +| |del| hr_payroll                             | Replaced by OCA module                          |
and the other the same

```suggestion
| |del| hr_payroll                             | Replaced by OCA module `payroll`                  |
```

2021-11-29 17:42 UTC, pedrobaeza approved these changes

2021-11-29 17:45 UTC, MiquelRForgeFlow commented
I think this should be put in `renamed_modules` dict instead, right?

2021-11-29 17:53 UTC, pedrobaeza commented
Well, if no conflict, the result is the same, and this way, we avoid possible errors if you already have a module with such name in the previous version, but no strong opinion on it anyways.

2021-11-29 18:06 UTC, pedrobaeza commented
@MiquelRForgeFlow, can you make us the favor of generating the analysis file?

2021-11-30 08:33 UTC, MiquelRForgeFlow approved these changes

2021-11-30 08:34 UTC, MiquelRForgeFlow commented
> can you make us the favor of generating the analysis file?

Ok

2021-11-30 08:38 UTC, merged