[14.0][FIX] account: take payment_ref only if move_name is NULL (or '')
OCA/OpenUpgrade pull request #3506
Opened 2022-08-05 08:11 UTC by MiquelRForgeFlow

As said in the point: # 2. try to match on statement move_name or payment_ref (if move_name empty)

That means we should avoid case where move_name is null, i.e, the statement line is not reconciled.

2022-08-05 18:07 UTC, pedrobaeza requested changes
Why not adding conditions in the WHERE about not null or similar for not having to do such weird comparisons?

2022-08-05 18:07 UTC, pedrobaeza commented on openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
> +            AND COALESCE(NULLIF(COALESCE(ap.move_name), ''),
This coalesce is doing nothing

2022-08-08 07:46 UTC, MiquelRForgeFlow commented
> Why not adding conditions in the WHERE about not null or similar for not having to do such weird comparisons?

Because they would become more wordy. Although it's a little illegible, it gets synthetically simple with those nested coalesce/nullif IMO.

2022-08-08 07:51 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py
> +            AND COALESCE(NULLIF(COALESCE(ap.move_name), ''),
Corrected.

2022-08-08 19:06 UTC, pedrobaeza approved these changes

2022-08-08 19:06 UTC, merged