[OU] hr_holidays: recompute duration_display in script in order to avoid errors for changes on the selection
OCA/OpenUpgrade pull request #3625
Opened 2022-11-22 23:12 UTC by etobella

Value was computed automatically on the migration, but it might become a problem if a module modified the selection values of request_unit

2022-11-23 09:39 UTC, MiquelRForgeFlow commented
![Selection_665](https://user-images.githubusercontent.com/25005517/203514162-ebc78632-188e-4730-9459-8651a01e0e5d.png) -> hr_holidays

2022-11-23 10:18 UTC, etobella commented
Sorry, for the typo error :laughing:

2022-11-23 10:20 UTC, MiquelRForgeFlow approved these changes

2022-11-23 22:16 UTC, pedrobaeza requested changes
I don't think restricting the computation is a correct formula, as there's no triggered error without restricting.


If you have specific types, the options are:

- Recompute again the affected records in your module filtering the specific type.
- Pre-add the DB column in your procedure, and later on end script launch the recomputation for all records.

But not to modify this way OpenUpgrade, sorry. IMO, this should be closed.

2022-11-23 23:43 UTC, etobella commented
This happens if you have installed hr_holidays_natural_period, an OCA module implemented by Tecnativa. 

The error is raised because when the system tries to read all records, natural_day is not expected.

2022-11-23 23:49 UTC, pedrobaeza commented
Can you put the error? Maybe the option is to add in pre the DB column, and do the computation of all records in end migration

2022-11-24 09:42 UTC, etobella commented
The error raised was the following:
```
2022-11-22 15:52:19,338 1 ERROR testick odoo.modules.registry: Failed to load registry 
2022-11-22 15:52:19,338 1 CRITICAL testick odoo.service.server: Failed to initialize database `testick`. 
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 793, in get
    return field_cache[record._ids[0]]
KeyError: 27

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 972, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 796, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'hr.leave(27,).leave_type_request_unit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/service/server.py", line 1201, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 455, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 199, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 422, in init_models
    env['base'].flush()
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5464, in flush
    self.recompute()
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5923, in recompute
    process(field)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5907, in process
    field.recompute(recs)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1155, in recompute
    self.compute_value(recs)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1177, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/auto/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4069, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo/auto/addons/hr_holidays/models/hr_leave.py", line 522, in _compute_duration_display
    if leave.leave_type_request_unit == 'hour'
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1021, in __get__
    self.compute_value(recs)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1177, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/auto/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4071, in _compute_field_value
    field.compute(self)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 555, in _compute_related
    record[self.name] = self._process_related(value[self.related_field.name])
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5703, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1109, in __set__
    self.write(protected_records, value)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 930, in write
    cache_value = self.convert_to_cache(value, records)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 2420, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for hr.leave.leave_type_request_unit: 'natural_day'
```

It would be cleaner to add the change to the end-migration, so I will apply the change. Thanks!

2022-11-24 09:58 UTC, MiquelRForgeFlow approved these changes

2022-11-26 11:28 UTC, pedrobaeza approved these changes

2022-11-26 11:28 UTC, merged

2022-11-26 11:28 UTC, pedrobaeza commented
For other times, the tag should `[OU-FIX]` instead of simply `[OU]`.