[13.0] l10n_be: migration script (account.account.tag)
OCA/OpenUpgrade pull request #3675
Opened 2023-01-04 16:22 UTC by remytms

Migrate account.account.tag to fit the new account.tax and its repartition lines.

2023-04-20 14:29 UTC, remytms commented
@sbidoul  this PR might interest you when migrating Belgian accounting. :)

2024-02-13 14:02 UTC, remytms commented
@marielejeune Can you give a look at this migration script? Thanks. :)

2024-02-13 14:12 UTC, marielejeune commented
Hi @remytms, I've seen your PR a few days ago, but I'm really not an accounting specialist and I don't think I've the competencies to functionally give any comment :/

2024-02-13 15:44 UTC, remytms commented
Thanks @marielejeune , if you know a Belgian accounting person do not hesitate to ping him/her.

2024-02-13 15:45 UTC, remytms commented
@luc-demeyer You may be interested by this pull request. :)

2024-02-23 09:34 UTC, marielejeune commented
Hi @remytms 
I am trying your script on a customer's database migration. I'll give you a complete feedback when I'll finish the migration. But I already have a functional question, since I'm not an accounting specialist. I got the following error: 

There is several account.tax found for the account.tax.template ID 141 '21% EU S.' that are used on account.move.line. Clean up account.tax by renaming your specific account.tax and migrate it via a dedicated script. The matching account.tax ID 133, 551

Indeed, both taxes with ID 133 and 551 have the same name, look the same, but one of them is linked to Company 1 (Belgian company) and the second one is linked to Company 2 (also Belgian company).

Is it a problem to have 2 taxes coming from the same tax template? If yes, what should have been done when initializing invoicing for these 2 companies? Duplicate the tax templates?

2024-02-26 15:25 UTC, fd-oncodna commented
Indeed as @marielejeune said I think this does not work if you have multiple companies in Belgium, as the taxes will be duplicated - but the tax templates, as they are created through XML. You should loop on the companies, chan,ge the signature of `find_account_tax(env, xmlid, account_tax_template)` to `find_account_tax(env, xmlid, account_tax_template, company)` and seach both the taxes and the move lines restricted to `company.

2024-02-27 10:01 UTC, marielejeune requested changes
I've tried to run your script on a DB with 2 Belgian companies, hence I've adapted it to loop on companies as @fd-oncodna suggested. Here are my comments, please have a look and tell me if it seems good to you:

2024-02-27 10:01 UTC, marielejeune commented on addons/l10n_be/migrations/13.0.2.0/post-migration.py
> +def find_account_tax(env, xmlid, account_tax_template):
```suggestion
def find_account_tax(env, xmlid, account_tax_template, company_id):
```

2024-02-27 10:01 UTC, marielejeune commented on addons/l10n_be/migrations/13.0.2.0/post-migration.py
> +    domain = [("type_tax_use", "=", account_tax_template.type_tax_use)]
```suggestion
    domain = [("type_tax_use", "=", account_tax_template.type_tax_use), ("company_id", "=", company_id)]
```

2024-02-27 10:01 UTC, marielejeune commented on addons/l10n_be/migrations/13.0.2.0/post-migration.py
> +        account_tax.name = account_tax_template.name
Loop on companies
```suggestion
    for company in env["res.company"].search([]):
        for xmlid, account_tax_template in get_account_tax_templates_iterator(env):
            account_tax = find_account_tax(env, xmlid, account_tax_template, company.id)

            if not account_tax:
                continue

            apply_new_tax_tags_on_account_tax(
                env, account_tax, account_tax_template
            )

            # Rename account_tax
            account_tax.name = account_tax_template.name
```

2024-02-27 10:01 UTC, marielejeune commented on addons/l10n_be/migrations/13.0.2.0/post-migration.py
> +    if not account_move_line_ids:
```suggestion
    if not account_move_line_ids or not old_tag_ids:
```

2024-03-13 14:19 UTC, remytms commented
@marielejeune @fd-oncodna Thanks a lot for your remark and suggestion about multi-company. Changes added.

2024-05-22 10:30 UTC, remytms commented
I close this PR in favor of this one: #4432

2024-05-22 10:30 UTC, closed without merging