[16.0][REF] product_form_purchase_link merged into purchase module
OCA/OpenUpgrade pull request #3762
Opened 2023-03-14 10:16 UTC by legalsylvain

Ref : https://github.com/OCA/purchase-workflow/pull/1762 (CC : CRogos)

CC : original author : @rousseldenis

2023-03-16 10:09 UTC, remytms approved these changes
LGTM

2023-03-16 10:27 UTC, pedrobaeza requested changes
Again put in `renamed_modules` instead of `merge_modules`.

2023-03-27 18:45 UTC, legalsylvain commented
Hi @pedrobaeza. Fixed.
thank you for your attentiveness !

2023-03-27 18:47 UTC, pedrobaeza approved these changes

2023-03-27 18:53 UTC, merged