[ADD] Use Case : noupdate_xml_change
OCA/OpenUpgrade pull request #3864
Opened 2023-05-09 00:20 UTC by legalsylvain

2023-05-31 13:15 UTC, remytms commented on docsource/use_cases/noupdate_xml_entry_changed.rst
> +   :header: "id", "header_spacing", "margin_bottom"
I think csv-table `header` is missing the key `name`.

2023-05-31 13:15 UTC, remytms commented on docsource/use_cases/noupdate_xml_entry_changed.rst
> +   :header: "id", "header_spacing", "margin_bottom"
Idem about the missing `name` column.

2023-05-31 13:34 UTC, legalsylvain commented on docsource/use_cases/noupdate_xml_entry_changed.rst
> +   :header: "id", "header_spacing", "margin_bottom"
thanks ! fixed.

2023-05-31 13:35 UTC, legalsylvain commented on docsource/use_cases/noupdate_xml_entry_changed.rst
> +   :header: "id", "header_spacing", "margin_bottom"
also fixed.

2023-05-31 13:43 UTC, remytms approved these changes
LGTM. Very helpfull. :)

2023-06-01 03:26 UTC, yostashiro reviewed
Nitpicking.

2023-06-01 03:26 UTC, yostashiro commented on docsource/use_cases/noupdate_xml_entry_changed.rst
> +++++++++
```suggestion
Rationale
+++++++++
```

2023-06-06 20:47 UTC, legalsylvain commented
hi @yostashiro, could you update your review ? 
thanks !

2023-06-17 05:00 UTC, yostashiro approved these changes
Thanks for the documentation!

2023-06-17 06:50 UTC, remi-filament requested changes
Minor type

2023-06-17 06:50 UTC, remi-filament commented on docsource/use_cases/noupdate_xml_entry_changed.rst
> +V12 table ``ir_act_window_view`` (With migration script)
Should be v15 here :
```suggestion
V15 table ``ir_act_window_view`` (With migration script)
```

2023-06-17 08:13 UTC, remi-filament approved these changes
Thanks !

2023-06-17 08:57 UTC, legalsylvain commented
/ocabot merge nobump

2023-06-17 08:59 UTC, merged