[WIP] [IMP] refactor intro
OCA/OpenUpgrade pull request #3924
Opened 2023-06-21 08:54 UTC by legalsylvain

- [x] describe more precisely openupgrade and openupgradelib.
- [x] describe more precisely old and new OpenUpgrade design
- [x] specifies that the version number corresponds to the target version. (a lot of issue are related to users that try to migrate a database from 11 to 12 using openupgrade 11...
- [x] add images for single and multi steps migration
- [ ] Add main reasons to realize a migration
- [ ] mention alternative to Openupgrade. (Odoo SA migration + create from scratch + imports).
- [ ] mention that OpenUpgrade is recommended by odoo S.A. for migrating odoo community edition instances.

2023-06-26 21:13 UTC, legalsylvain commented
this one is ready for review. 
CC : @bguillot, @etobella.

2023-06-27 15:02 UTC, vdewulf requested changes

2023-06-27 15:02 UTC, vdewulf commented on docsource/intro.rst
>  Odoo is an open source business application suite and development platform.
==> open core instead of open source? (if we want to be honest)

2023-06-27 15:02 UTC, vdewulf commented on docsource/intro.rst
>  Odoo. This is a community initiative, as the open source version of Odoo
This is a community initiative (under the OCA umbrella) + link to oca website?

2023-06-27 15:02 UTC, vdewulf commented on docsource/intro.rst
> +Community Edition does not support migrations from one major release to another.
Odoo Community Edition (CE)
==> add the acronym because used later

2023-06-27 15:02 UTC, vdewulf commented on docsource/intro.rst
> +and that the OpenUpgrade logo includes the ant present in the *OpenERP* logo.
Where is this logo? I don't know it!

2023-06-27 15:02 UTC, vdewulf commented on docsource/intro.rst
> +Why migrate to a more recent major version
you could add Daniel's video on this topic from OCA Days 2020: 
https://youtu.be/u7_k8lCZeY0

2023-06-27 15:02 UTC, vdewulf commented on docsource/intro.rst
> +  Only the latest versions are patched, so older versions are left with security breeches that can be exploited.
the 3 latest versions are patched by Odoo S.A.

2023-06-27 15:02 UTC, vdewulf commented on docsource/images/oca-modules-evolution.png
Add the axes X and Y and legend (blue, red...)

2023-06-27 15:02 UTC, vdewulf commented on docsource/intro.rst
> +   are available are only available if you subscribe to Odoo Enterprise Edition.
dubble "are" in the sentence

2023-06-27 15:02 UTC, vdewulf commented on docsource/intro.rst
> +   but only some of it.
but only some of it (in particular, you won't have the history and links between data, like the invoices for all customers for example).

2023-06-27 15:41 UTC, legalsylvain commented on docsource/intro.rst
> +and that the OpenUpgrade logo includes the ant present in the *OpenERP* logo.
https://oca.github.io/OpenUpgrade/

2023-06-27 19:16 UTC, legalsylvain commented on docsource/intro.rst
>  Odoo is an open source business application suite and development platform.
;-) done.

2023-06-27 19:16 UTC, legalsylvain commented on docsource/intro.rst
>  Odoo. This is a community initiative, as the open source version of Odoo
Done.

2023-06-27 19:16 UTC, legalsylvain commented on docsource/intro.rst
> +Community Edition does not support migrations from one major release to another.
Indeed. done.

2023-06-27 19:16 UTC, legalsylvain commented on docsource/intro.rst
> +Why migrate to a more recent major version
Good Idea ! done.

2023-06-27 19:17 UTC, legalsylvain commented on docsource/intro.rst
> +  Only the latest versions are patched, so older versions are left with security breeches that can be exploited.
done, with a link to the Odoo policy.
https://www.odoo.com/documentation/master/administration/maintain/supported_versions.html#what-s-the-support-status-of-my-odoo

2023-06-27 19:17 UTC, legalsylvain commented on docsource/intro.rst
> +   are available are only available if you subscribe to Odoo Enterprise Edition.
fixed.

2023-06-27 19:17 UTC, legalsylvain commented on docsource/intro.rst
> +   but only some of it.
added.

2023-06-27 19:24 UTC, legalsylvain commented on docsource/images/oca-modules-evolution.png
I added a legend. I find it quite explicit : 

![image](https://github.com/OCA/OpenUpgrade/assets/3407482/2b0031ea-1ce4-482a-aec4-df93e23bae6b)

it's just to indicate a growth trend. but i can remove it, if it's not understandable, or if it doesn't add anything.

2023-06-27 19:24 UTC, legalsylvain commented
thanks @vdewulf for your review. I applied your suggestion. let me know if there are some other points to fix.

2023-06-28 11:58 UTC, vdewulf approved these changes
Thanks for integrating my comments.

2023-07-12 11:38 UTC, etobella approved these changes

2023-07-12 11:41 UTC, MiquelRForgeFlow approved these changes
LGTM

2023-07-12 15:23 UTC, legalsylvain commented
/ocabot merge nobump

2023-07-12 15:33 UTC, merged