[16.0][OU-ADD] survey: Nothing to do
OCA/OpenUpgrade pull request #3946
Opened 2023-06-29 09:12 UTC by duyquyen96

Nothing to do

2023-06-29 09:47 UTC, legalsylvain commented
/ocabot migration survey

2023-07-13 12:24 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/survey/16.0.3.5/upgrade_analysis_work.txt
> +DEL ir.actions.server: survey.survey_action_server_clean_test_answers (noupdate)
needs to be deleted in post-migration

2023-10-18 14:44 UTC, victoralmau requested changes
I think it would be a good idea to rename the xmlid of some views that are "_same_", for example `question_result_number_or_date` (v15) and `question_result_number_or_date_or_datetime` (v16) to keep a good compatibility if someone had inherited from some view.

2023-10-18 14:44 UTC, victoralmau commented on openupgrade_scripts/scripts/survey/16.0.3.5/upgrade_analysis_work.txt
> +survey       / survey.question          / question_placeholder (char)   : NEW hasdefault: compute
IMO I think you should create the column and set the correct value in the migration to avoid odoo to do the compute and optimize time.

2023-10-18 15:26 UTC, legalsylvain commented
> I think it would be a good idea to rename the xmlid of some views that are "same", for example question_result_number_or_date (v15) and question_result_number_or_date_or_datetime (v16) to keep a good compatibility if someone had inherited from some view.

Could you elaborate ? I dont' understand in wich case it is problematic. Thanks !

2023-10-18 15:30 UTC, pedrobaeza commented
Example: manually created views inheriting that one. Of course that "shouldn't happen", but in case you have some rebel users doing that on their own, the original view can't be auto-deleted, as there's a children view that prevents it, and you end up with several views for the same model or at least dead views.

2023-10-18 19:28 UTC, legalsylvain commented
> Example: manually created views inheriting that one. Of course that "shouldn't happen", but in case you have some rebel users doing that on their own, the original view can't be auto-deleted, as there's a children view that prevents it, and you end up with several views for the same model or at least dead views.

I have reservations about asking for these changes in a review. 
If someone encounters this case, he can make the change in a PR, but if it's systematically requested, it risks adding work to contributors, whereas it's a case of use "that shouldn't happen", as you say.

If this request is ["suggestion - non blocking"](https://conventionalcomments.org/), then everything's OK.

2024-03-08 10:59 UTC, pedrobaeza commented
Superseded by #4334 

Each field addition or deletion should be analyzed with care, as there can be consequences or changes of behavior. Please check the ones I have done in the other PR as reference.

2024-03-08 10:59 UTC, closed without merging