[15.0][Fix] mail: _migrate_placeholder_html should remove '| safe'
OCA/OpenUpgrade pull request #4143
Opened 2023-10-06 08:57 UTC by cuongnmtm

This will fix the issue when Odoo renders this wrong syntax

Content in email template body v14:

`${object.company_id.email | safe}`

Content in email template body v15 (after migrate data):

`<t t-out="object.company_id.email | safe">`

Error:

```
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
TypeError: unsupported operand type(s) for |: 'str' and 'NoneType'
```

2024-12-19 12:22 UTC, MiquelRForgeFlow commented
@cuongnmtm could you rebase?

2024-12-20 09:35 UTC, hbrunn requested changes

2024-12-20 09:35 UTC, hbrunn commented on openupgrade_scripts/scripts/mail/15.0.1.5/post-migration.py
> +    string = re.sub(r"\s?\|\s?safe\s?", "", string)
there can be much more [filters](https://jinja.palletsprojects.com/en/stable/templates/#filters) - could you extend the regex to just replace anything after the first pipe?

2025-03-13 16:42 UTC, MiquelRForgeFlow commented
Done in https://github.com/OCA/OpenUpgrade/pull/4438.

2025-03-13 16:42 UTC, closed without merging