[16.0][OU-ADD] l10n_es: Nothing to do
OCA/OpenUpgrade pull request #4144
Opened 2023-10-06 11:32 UTC by stefan-tecnativa

cc @Tecnativa TT42251

@pedrobaeza please review!

2023-10-06 13:06 UTC, legalsylvain commented on docsource/modules150-160.rst
> +| l10n_es                                         |                      |Nothing to do                                                 |
```suggestion
| l10n_es                                         |                      |Nothing to do                                    |
```

2023-10-06 13:15 UTC, stefan-tecnativa commented on docsource/modules150-160.rst
> +| l10n_es                                         |                      |Nothing to do                                                 |
I didn't noticed it. Thanks!

2023-10-06 13:29 UTC, legalsylvain approved these changes

2023-10-19 10:19 UTC, chienandalu reviewed
Depends on

- [x] https://github.com/OCA/OpenUpgrade/pull/4070
- [ ] https://github.com/OCA/OpenUpgrade/pull/3870
- [ ] https://github.com/OCA/OpenUpgrade/pull/3871

2023-10-20 09:08 UTC, legalsylvain commented
/ocabot migration l10n_es

2023-10-25 13:27 UTC, stefan-tecnativa commented
@pedrobaeza All the modules it depended on have been merged. Is it possible to merge the PR?

2023-10-25 13:33 UTC, chienandalu approved these changes

2023-10-25 14:13 UTC, pedrobaeza requested changes

2023-10-25 14:13 UTC, pedrobaeza commented on docsource/modules150-160.rst
> +| l10n_es                                         |                      |Nothing to do                                    |
You have put it the wrong place:

```suggestion
| l10n_es                                         | Nothing to do        |                                               |
```

2023-10-25 14:13 UTC, pedrobaeza commented
And rebase over latest changes.

2023-10-25 14:19 UTC, stefan-tecnativa commented
@pedrobaeza thanks for the review and the comments!

2023-10-25 17:39 UTC, pedrobaeza approved these changes

2023-10-25 17:40 UTC, merged