[15.0] [OU-ADD] digest
OCA/OpenUpgrade pull request #4167
Opened 2023-10-17 09:30 UTC by cuongnmtm

Load noupdate_changes

2023-10-17 10:03 UTC, legalsylvain commented
/ocabot migration digest

2023-10-18 13:51 UTC, rvalyi approved these changes

2023-12-04 11:57 UTC, chienandalu requested changes
This strikes back in v16 when upgrading mass_mailing, which needs the new hooks provided by these templates

2023-12-04 11:57 UTC, chienandalu commented on openupgrade_scripts/scripts/digest/15.0.1.1/post-migration.py
> +    openupgrade.load_data(env.cr, "digest", "15.0.1.1/noupdate_changes.xml")
You should remove translations delete translations as well as in https://github.com/OCA/OpenUpgrade/blob/877ae6638a01bcdca7c9281f3e3bb9ca94fd5af5/openupgrade_scripts/scripts/digest/16.0.1.1/post-migration.py#L20

2023-12-22 09:16 UTC, cuongnmtm commented on openupgrade_scripts/scripts/digest/15.0.1.1/post-migration.py
> +    openupgrade.load_data(env.cr, "digest", "15.0.1.1/noupdate_changes.xml")
Thanks @chienandalu

2023-12-22 09:17 UTC, chienandalu approved these changes
Thanks :)

2023-12-22 09:33 UTC, chienandalu approved these changes

2023-12-31 16:58 UTC, merged