[16.0][OU-ADD] repair: Migration scripts for v16
OCA/OpenUpgrade pull request #4302
Opened 2024-02-14 14:11 UTC by remi-filament

2024-02-14 17:09 UTC, remi-filament commented
/ocabot migration repair

2024-02-14 17:22 UTC, pedrobaeza commented
/ocabot migration repair

<dependency>Depends on : 

- stock : #4291
- sale_management : #4014
- account : #4070</dependency>

2025-05-19 13:13 UTC, carlos-lopez-tecnativa approved these changes
Please rebase the branch to run the CI.
Tested locally and it’s working fine.

2025-05-19 13:13 UTC, carlos-lopez-tecnativa commented
ping @pedrobaeza @MiquelRForgeFlow

2025-05-19 13:31 UTC, remi-filament commented
Thanks @carlos-lopez-tecnativa rebase done

2025-05-19 13:36 UTC, MiquelRForgeFlow approved these changes
LGTM

2025-05-20 04:47 UTC, pedrobaeza requested changes

2025-05-20 04:47 UTC, pedrobaeza commented on openupgrade_scripts/scripts/repair/16.0.1.0/post-migration.py
> +    openupgrade.load_data(env.cr, "repair", "16.0.1.0/noupdate_changes.xml")
Reset the translations for the fields "name" and "description" of `mail_template_repair_quotation`

2025-05-20 04:47 UTC, pedrobaeza commented on openupgrade_scripts/scripts/repair/16.0.1.0/post-migration.py
> +    _compute_repair_price_total(env, "repair.line")
This is totally useless.

```suggestion
```

Odoo is already computing these fields:

![image](https://github.com/user-attachments/assets/349be046-d87a-4840-8720-68a7ffcbd34d)

In fact, the improvement will be to do this by SQL instead.

2025-05-20 04:47 UTC, pedrobaeza commented on openupgrade_scripts/scripts/repair/16.0.1.0/upgrade_analysis_work.txt
> +repair       / stock.picking.type       / is_repairable (boolean)       : NEW hasdefault: compute
Is the default a good value?

2025-06-12 13:43 UTC, remi-filament commented on openupgrade_scripts/scripts/repair/16.0.1.0/upgrade_analysis_work.txt
> +repair       / stock.picking.type       / is_repairable (boolean)       : NEW hasdefault: compute
Hi @pedrobaeza thanks for your review
I think it is, it is checking whether the type is not incoming and has other types pointing to it with for return.
Anyhow, this new field allows then to create repair from the incoming picking so I suppose it is a good thing to have it possible by default ?

2025-06-12 13:47 UTC, remi-filament commented on openupgrade_scripts/scripts/repair/16.0.1.0/post-migration.py
> +    _compute_repair_price_total(env, "repair.line")
Fine I remove it then.
these methods are calling account.tax compute_all() function which is quite complex and I think is better done in python rather than in SQL.

2025-06-12 13:47 UTC, remi-filament commented on openupgrade_scripts/scripts/repair/16.0.1.0/post-migration.py
> +    openupgrade.load_data(env.cr, "repair", "16.0.1.0/noupdate_changes.xml")
Done

2025-06-12 17:21 UTC, pedrobaeza approved these changes

2025-06-12 17:21 UTC, merged