[17.0][OU-ADD] account: migration to 17.0
OCA/OpenUpgrade pull request #4457
Opened 2024-06-13 06:30 UTC by duong77476-viindoo

2024-06-13 06:36 UTC, pedrobaeza commented
/ocabot migration account

2024-06-27 06:22 UTC, duong77476-viindoo commented
@flachica Hello, i apply your fix here, please notify me if you have something in your mind :v

2024-06-27 07:47 UTC, flachica commented
> @flachica Hello, i apply your fix here, please notify me if you have something in your mind :v

I will close my PR and internally use this branch. Thanks for you amazing work.

2024-06-27 08:05 UTC, flachica approved these changes

2024-07-09 07:27 UTC, rvalyi commented
Hello, I'm creating a new analysis tool called odoo-module-diff, it's explained here: https://github.com/akretion/odoo-module-diff

To review or complete the PR, you might be interested by these key commits of the account module migration to 17.0:
https://github.com/akretion/odoo-module-diff-analysis/tree/main/17.0/account

2024-09-19 09:47 UTC, ecino commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +    "account_tax": [("description", "invoice_label", "JSONB")],
When trying the script, I get the following error:

```
psycopg2.errors.DatatypeMismatch: column "invoice_label" is of type jsonb but expression is of type character varying
LINE 4: ...             UPDATE account_tax SET invoice_label=description
```

2024-09-19 09:49 UTC, duong77476-viindoo commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +    openupgrade.copy_columns(env.cr, _columns_copies)
@ecino Ok maybe do same here

2024-10-28 15:38 UTC, hbrunn requested changes

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +    )
as we don't do anything with this ourselves, we should leave it to the ORM to create this column. It will be available to the depending modules anyways

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +    )
see above

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/upgrade_analysis_work.txt
> +# DONE pre-migration: Create column then in sale_stock, purchase_stock will fill it in pre, pr: https://github.com/odoo/odoo/pull/118954
this and the above should be nothing to do

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +                WHEN end_month IN (false, NULL) THEN 'days_after'
```suggestion
                WHEN end_month IS NULL OR NOT end_month THEN 'days_after'
```

but given the ELSE branch below does the same, we can just remove this

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +                WHEN end_month = true AND months > 1 THEN 'days_end_of_month_on_the'
```suggestion
                WHEN end_month = true AND COALESCE(months, 0) = 0 AND days_after > 0 THEN 'days_end_of_month_on_the'
                WHEN end_month = true AND COALESCE(months, 0) = 0 THEN 'days_after_end_of_month'
                WHEN end_month = true AND months > 1 THEN 'days_end_of_month_on_the'
```

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +                WHEN end_month IN (false, NULL) THEN (months*30) + days
we can't map all possible configurations of v16 here, so cover the two cases that match exactly, do a heuristic that might be what the user wants for the rest

```suggestion
                WHEN end_month = true AND months <= 1
                THEN COALESCE(days, 0) + COALESCE(days_after, 0)
                ELSE COALESCE(months, 0)*30 + COALESCE(days, 0) + COALESCE(days_after, 0)
```

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +def _account_payment_term_migration(env):
this function should go to post-migration to avoid having to create fields manually

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +def _force_install_account_payment_term_module_module(env):
do this conditionally if we set `delay_type=days_end_of_month_on_the` above, pre-create column  `days_next_month`(https://github.com/OCA/OCB/blob/17.0/addons/account_payment_term/models/account_payment_term.py#L16) and set it to `days_after`, subtract from `days` as we add it above in those lines too

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +):
move to post-migration

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +    openupgrade.logged_query(
move to post-migration, use [openupgrade.map_values](https://oca.github.io/openupgradelib/API.html#openupgradelib.openupgrade.map_values)

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +        if company_id == env.company.id:
why this restriction?

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +    convert_column_translatable(env.cr, "account_tax", "description", "jsonb")
in the spirit of preserving data, I'd rather copy `description` with type `None`, then run `convert_column_translatable`on the result

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +    """
this code will be much simpler in post-migrate. I also suggest to add a column in tax groups pointing to the tax group they originate from, this will make it simpler for localizations to find them and do something with them if necessary

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +        imd.write({"name": f"{first_company_id}_{imd.name}"})
better clone this one and write on the clone, then it's less hassle for localization to process them

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +            ),
third case is both company_id and res_id are null

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +    openupgrade.logged_query(
I think it's useful to add `openupgrade.convert_from_company_dependent` which is the inverse of [`convert_to_company_dependent`](https://oca.github.io/openupgradelib/API.html#openupgradelib.openupgrade.convert_to_company_dependent)

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +def _res_partner_bank_create_column(env):
remove

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/upgrade_analysis_work.txt
> +# DONE create column in pre-migration and compute using orm in end-migration
should be nothing to do

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/end-migration.py
> +# Copyright 2024 Viindoo Technology Joint Stock Company (Viindoo)
remove whole file

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/upgrade_analysis_work.txt
> +# DONE: removed in post-migration
as written above, I think we should keep them

2024-10-28 15:38 UTC, hbrunn commented on openupgrade_scripts/scripts/account/17.0.1.2/upgrade_analysis_work.txt
> +DEL ir.model.constraint: account_sequence.constraint_account_move_unique_name
this one is actually added in account now, so we need to uniquify names.

And the whole _work file needs updating from the current analysis file, it contains confusing bogus entries

2024-10-28 15:39 UTC, hbrunn commented
I'll create a followup-PR next Monday of nobody else has picked this up until then

2024-10-29 01:10 UTC, duong77476-viindoo commented
> I'll create a followup-PR next Monday of nobody else has picked this up until then

Thank you sir

2024-11-04 20:41 UTC, hbrunn commented
I didn't manage to finish this today, so I just pushed an [intermediate version](https://github.com/hbrunn/OpenUpgrade/tree/17.0-account) on my fork. Still working on a correct payment term migration, tax groups should be fine already.

2024-11-07 20:52 UTC, pedrobaeza commented
@hbrunn is this finished on your side (or on hold). It's for resuming from here.

2024-11-07 22:30 UTC, hbrunn commented
my comments from https://github.com/OCA/OpenUpgrade/pull/4457#discussion_r1819149393 down need addressing still, so if you've the time, please resume from there

2024-11-08 13:18 UTC, hbrunn commented
PS: I'll continue with this on Monday if I don't hear anything to the contrary

2024-11-08 13:34 UTC, pedrobaeza commented
I'm today resuming this, so probably it will be done. I'll tell you.

2024-11-09 11:31 UTC, pedrobaeza commented on openupgrade_scripts/scripts/account/17.0.1.2/pre-migration.py
> +    )
@hbrunn It's OK to pre-create this column for avoiding to trigger the computation (although empty in this module), so we light the process. I'm reverting the change you have done.

2024-11-11 04:25 UTC, hbrunn commented
I don't find any new commits on https://github.com/Tecnativa/OpenUpgrade/commits/17.0-account - what are you working on so that I can do something else today?

2024-11-11 07:01 UTC, pedrobaeza commented
I'm still working on this.

2024-11-11 07:04 UTC, hbrunn commented
today?

2024-11-11 07:05 UTC, pedrobaeza commented
Yes, I will push my result at the end of the morning.

2024-11-11 07:07 UTC, hbrunn commented
great, then I'll pick it up from there and do some more reviews meanwhile

2024-11-11 13:58 UTC, hbrunn commented
?

2024-11-11 14:43 UTC, pedrobaeza commented
I have opened https://github.com/OCA/OpenUpgrade/pull/4662, but it's still not finished. I'm just stuck at the new `invoice_label` to fill proper data. I have reviewed/reworked till https://github.com/OCA/OpenUpgrade/pull/4662/files#diff-22f22a0c72f96258826774abe5ffb855f21883cf30e51b7e81fbcaaca048214aR275

2024-11-11 14:45 UTC, closed without merging