[17.0][OU-ADD] hr: migration to 17.0
OCA/OpenUpgrade pull request #4462
Opened 2024-06-13 06:56 UTC by duong77476-viindoo

2024-06-13 07:00 UTC, pedrobaeza commented
/ocabot migration hr

2024-07-09 07:26 UTC, rvalyi commented
Hello, I'm creating a new analysis tool called odoo-module-diff, it's explained here: https://github.com/akretion/odoo-module-diff

To review or complete the PR, you might be interested by these key commits of the hr module migration to 17.0:
https://github.com/akretion/odoo-module-diff-analysis/tree/main/17.0/hr

2025-01-15 17:42 UTC, etobella commented
/ocabot rebase

2025-01-15 17:58 UTC, hbrunn requested changes

2025-01-15 17:58 UTC, hbrunn commented on openupgrade_scripts/scripts/hr/17.0.1.1/end-migration.py
> +        FROM hr_employee
```suggestion
        FROM hr_employee
        WHERE work_contact_id IS NOT NULL AND address_home_id IS NOT NULL
        AND work_contact_id<>address_home_id
```

as the merge function chokes if any of them is not set or they are the same, which all are perfectly valid settings in v16

2025-01-16 06:04 UTC, hbrunn approved these changes

2025-02-17 11:51 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/hr/17.0.1.1/upgrade_analysis_work.txt
> +# NOTHING TO DO
I think many2many table has to be adapted / renamed at least.

2025-02-17 11:51 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/hr/17.0.1.1/upgrade_analysis_work.txt
> +# DONE: removed in pre-migration
```suggestion
# DONE: removed in post-migration
```

2025-02-17 11:51 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/hr/17.0.1.1/upgrade_analysis_work.txt
> +# DONE: renamed in pre-migration and removed in post-migration
explain why explicitly

2025-02-17 11:51 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/hr/17.0.1.1/upgrade_analysis_work.txt
> +# DONE: removed in pre-migration
```suggestion
# DONE: removed in post-migration
```

2025-02-17 11:51 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/hr/17.0.1.1/upgrade_analysis_work.txt
> +# DONE: removed in pre-migration
```suggestion
# DONE: removed in post-migration
```

2025-02-17 11:51 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/hr/17.0.1.1/post-migration.py
> +    "hr.dep_sales",
In fact, don't delete this record with delete_records_safely_by_xml_id, because the record was moved to demo data, but note deleted.

For `hr.dep_sales`, I think you should delete only the xmlid (not the record) with:
```python
env["ir.model.data"].search(
                [("module", "=", "hr"), ("name", "=", "dep_sales")], limit=1
            ).unlink()
```

2025-02-23 12:27 UTC, pedrobaeza commented
I'm superseding this PR to add latest changes.

2025-02-28 12:22 UTC, JordiBForgeFlow commented
@pedrobaeza should this PR then be closed, if you are superseding?

2025-02-28 12:22 UTC, pedrobaeza commented
Yes, totally, this one is doing destructive things that are not correct.

2025-02-28 12:26 UTC, closed without merging

2025-03-02 11:19 UTC, pedrobaeza commented on openupgrade_scripts/scripts/hr/17.0.1.1/post-migration.py
> +    "hr.dep_sales",
I think it's correct to delete safely. Demo data are not in production databases, so at the end, if the department is not used, it can be deleted. If not, the method will do the rest.

2025-03-02 11:36 UTC, pedrobaeza commented
@JordiBForgeFlow here you have it: #4794