[17.0][OU-ADD] project: migrate to 17.0
OCA/OpenUpgrade pull request #4469
Opened 2024-06-13 07:56 UTC by duong77476-viindoo

2024-06-13 08:10 UTC, pedrobaeza commented
/ocabot migration project

2024-07-09 07:23 UTC, rvalyi commented
Hello, I'm creating a new analysis tool called odoo-module-diff, it's explained here: https://github.com/akretion/odoo-module-diff

To review or complete the PR, you might be interested by these key commits of the project module migration to 17.0:
https://github.com/akretion/odoo-module-diff-analysis/tree/main/17.0/project

2024-07-11 01:25 UTC, duong77476-viindoo commented
> Hello, I'm creating a new analysis tool called odoo-module-diff, it's explained here: https://github.com/akretion/odoo-module-diff
> 
> To review or complete the PR, you might be interested by these key commits of the project module migration to 17.0: https://github.com/akretion/odoo-module-diff-analysis/tree/main/17.0/project

Hello @rvalyi if you feel like i'm missing something, just make a review. In case i've missed yours feel free to cherry-pick or copy code from this PR to your own fork repository .
FYI, normally i don't go over all the commit changes just a few of those are fine

2025-03-01 03:39 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/project/17.0.1.3/post-migration.py
> +    openupgrade.load_data(env, "project", "17.0.1.3/noupdate_changes.xml")
to delete translations of project_message_user_assigned and rating_project_request_email_template

2025-03-01 03:39 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/project/17.0.1.3/upgrade_analysis_work.txt
> +project      / project.task             / planned_hours (float)         : DEL
to put this above, below the allocated_hours

2025-03-01 03:39 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/project/17.0.1.3/upgrade_analysis_work.txt
> +project      / project.task             / kanban_state (selection)      : DEL required, selection_keys: ['blocked', 'done', 'normal']
to explain here thing done in post-migration, how it affects state

2025-03-01 03:39 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/project/17.0.1.3/upgrade_analysis_work.txt
> +project      / project.task             / state (selection)             : NEW required, selection_keys: ['01_in_progress', '02_changes_requested', '03_approved', '04_waiting_normal', '1_canceled', '1
to put above, below kanban_state

2025-03-01 03:39 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/project/17.0.1.3/post-migration.py
> +            WHEN kanban_state = 'done' THEN '1_done'
1_done if is_closed = TRUE else 03_approved

2025-03-01 03:39 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/project/17.0.1.3/post-migration.py
> +            WHEN kanban_state = 'blocked' THEN '04_waiting_normal'
1_canceled  if is_closed = TRUE else 02_changes_requested

2025-03-01 03:39 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/project/17.0.1.3/post-migration.py
> +            ELSE '01_in_progress'
04_waiting_normal if not any(depend_on_ids.is_closed = False) else 01_in_progress

2025-03-14 14:15 UTC, carlos-lopez-tecnativa requested changes
Tested and working, but I think some parts of the migration could be fine-tuned.

TT49321

CC: @pedrobaeza @CarlosRoca13

2025-03-14 14:15 UTC, carlos-lopez-tecnativa commented on openupgrade_scripts/scripts/project/17.0.1.3/post-migration.py
> +    )
I think this update should be more specific. Please consider the following cases:

- This field has a [default=True](https://github.com/odoo/odoo/blob/3467eb69d61a8660b74a1f315673a0da51162aeb/addons/project/models/project_task.py#L163), so currently, all records are set to True.
- It should be set to `True` when the task has an assigned `project_id` but does not have a `parent_id`. Otherwise, it should be set to `False`.
https://github.com/odoo/odoo/blob/3467eb69d61a8660b74a1f315673a0da51162aeb/addons/project/models/project_task.py#L1006-L1046

2025-03-14 14:15 UTC, carlos-lopez-tecnativa commented on openupgrade_scripts/scripts/project/17.0.1.3/post-migration.py
> +        SET state = CASE
This is a newly computed stored field. Please pre-create the column in the `pre-migration` script; otherwise, at this stage, Odoo will compute the field using the ORM, which may result in slow performance.

2025-03-14 14:15 UTC, carlos-lopez-tecnativa commented on openupgrade_scripts/scripts/project/17.0.1.3/upgrade_analysis_work.txt
> +project      / project.task.recurrence  / repeat_type (selection)       : selection_keys is now '['forever', 'until']' ('['after', 'forever', 'until']')
The option `repeat_type='after'` has been removed. Have you changed this to a similar alternative? It can be converted to `until`, and the field `repeat_until` can be recomputed based on `repeat_number` to maintain the behavior from V16.

2025-03-14 14:15 UTC, carlos-lopez-tecnativa commented on openupgrade_scripts/scripts/project/17.0.1.3/upgrade_analysis_work.txt
> +project      / project.update           / closed_task_count (integer)   : NEW
It's a new field, but I think it would be useful to set this value in the `post-migration` script using the field [date_end](https://github.com/odoo/odoo/blob/3467eb69d61a8660b74a1f315673a0da51162aeb/addons/project/models/project_task.py#L1173). The goal would be to compute which tasks are considered closed based on the `create_date` of `project.update`.

Example:

**Tasks:**

- Task 1: date_end = 2025-01-01
- Task 2: date_end = 2025-01-10
- Task 3: date_end = 2025-02-15

**Project Updates:**

- Project update 1: create_date = 2025-01-31 → closed_task_count = 2
- Project update 2: create_date = 2025-03-31 → closed_task_count = 3

What do you think?

2025-03-14 14:15 UTC, carlos-lopez-tecnativa commented on openupgrade_scripts/scripts/project/17.0.1.3/upgrade_analysis_work.txt
> +project      / project.update           / task_count (integer)          : NEW
A similar case to `closed_task_count`, but this time considering all tasks created before the `project.update`. In this case, we would use the `create_date` from `project.task` to compare it with the `create_date` from `project.update`.

Example:

Tasks:

- Task 1: create_date = 2025-01-01
- Task 2: create_date = 2025-01-10
- Task 3: create_date = 2025-02-15

Project Updates:

- Project update 1: create_date = 2025-01-31 → task_count = 2
- Project update 2: create_date = 2025-03-31 → task_count = 3

What do you think?

2025-03-28 20:09 UTC, pedrobaeza commented
Superseded by #4892

2025-03-28 20:09 UTC, closed without merging