[17.0][OU-ADD] project_todo: migrate to 17.0
OCA/OpenUpgrade pull request #4470
Opened 2024-06-13 07:58 UTC by duong77476-viindoo

2024-06-13 08:10 UTC, pedrobaeza commented
/ocabot migration project_todo

2025-03-14 17:46 UTC, carlos-lopez-tecnativa requested changes
Tested and working, just a minor observation.

2025-03-14 17:46 UTC, carlos-lopez-tecnativa commented on openupgrade_scripts/scripts/project_todo/17.0.1.0/pre-migration.py
> +        FROM note_note
Please migrate followers from `note.note` to `project.task`, as this is currently missing.

![image](https://github.com/user-attachments/assets/1249a061-4a5f-4bf6-9d1a-d8c39aec9e6b)

2025-03-15 09:39 UTC, pedrobaeza commented on openupgrade_scripts/scripts/project_todo/17.0.1.0/pre-migration.py
> +        FROM note_note
As I'm understanding this, the problem is not with `openupgradelib`, but the fact that is not a renaming, but an INSERT INTO which is not caring about the followers.

2025-03-18 15:01 UTC, carlos-lopez-tecnativa commented on openupgrade_scripts/scripts/project_todo/17.0.1.0/pre-migration.py
> +        FROM note_note
> As I'm understanding this, the problem is not with `openupgradelib`, but the fact that is not a renaming, but an INSERT INTO which is not caring about the followers.

I’m sorry, please disregard my previous comment. I tested with a database containing demo data, and Odoo deleted the address that was removed from the code (as a private address). But as you said, `openupgradelib` handles the followers [here](https://github.com/OCA/openupgradelib/blob/95e59ab331c312ac5bdaa399aaa6ddf18ffe616a/openupgradelib/openupgrade.py#L1231). And here, it calls `merge_models` https://github.com/OCA/OpenUpgrade/pull/4470/files#diff-1937c9b8d895188c69985aa078d667cde3ed4c8f72ff658c214a66c1307c4b95R111

V16
![image](https://github.com/user-attachments/assets/007fb250-7d8a-4717-bb14-e057ea55a8bc)

V17 after migration
![image](https://github.com/user-attachments/assets/10c8c186-1c58-4c8c-9a1a-77d92dc54f64)

The manual contacts are kept, but the contacts like Deco or Azure are removed. I suspect this is because some demo data was dropped, and this caused the cascade removal.

2025-04-01 12:32 UTC, carlos-lopez-tecnativa commented
@ndd-odoo please rebase the branch

2025-04-03 12:08 UTC, pedrobaeza commented on openupgrade_scripts/scripts/project_todo/17.0.1.0/pre-migration.py
> +        FROM note_note
openupgradelib `merge_models` method already cares about the followers move, so nothing more to do here.

2025-04-03 14:24 UTC, pedrobaeza commented
Superseded by #4914

2025-04-03 14:24 UTC, closed without merging