[17.0][OU-ADD] stock: migrate to 17.0
OCA/OpenUpgrade pull request #4557
Opened 2024-09-18 20:15 UTC by acpMicrocom

2024-09-19 08:16 UTC, legalsylvain commented
/ocabot migration stock

2024-10-12 01:37 UTC, xtanuiha requested changes

2024-10-12 01:37 UTC, xtanuiha commented on openupgrade_scripts/scripts/stock/17.0.1.1/upgrade_analysis_work.txt
> +stock        / stock.move.line          / quantity (float)              : NEW hasdefault: compute
Due to the change of Odoo field names, I think it is necessary to rename the field 'qty_done' to 'quantity' in pre-migraion.py

2024-10-12 01:37 UTC, xtanuiha commented on openupgrade_scripts/scripts/stock/17.0.1.1/upgrade_analysis_work.txt
> +stock        / stock.move               / quantity_done (float)         : DEL
It is necessary to rename the columns in the database in pre-migration.py to ensure that the data of the quantity_done field is migrated to the quantity field.

2024-10-12 01:37 UTC, xtanuiha commented on openupgrade_scripts/scripts/stock/17.0.1.1/upgrade_analysis_work.txt
> +stock        / stock.scrap              / move_ids (one2many)           : NEW relation: stock.move
I think it is necessary to deal with the structural change here. Something like this.
```python
def _update_stock_move_scrap(env):
    sql = 'SELECT id,move_id FROM stock_scrap WHERE move_id IS NOT NULL;'
    env.cr.execute(sql)
    scrap_dict = env.cr.dictfetchall()
    scrap_dict = dict([(item['id'], item['move_id']) for item in scrap_dict])
    for scrap in env['stock.scrap'].search([('id', 'in', list(scrap_dict.keys()))]):
        scrap.write({'move_ids': [(4, scrap_dict[scrap.id])]})
```

2024-10-18 14:59 UTC, rvalyi commented
for reference the 4 key commits for the stock migration to v17: https://github.com/akretion/odoo-module-diff-analysis/tree/main/17.0/stock

2024-10-30 05:41 UTC, xtanuiha approved these changes

2024-10-30 12:17 UTC, rvalyi requested changes
the commit message is wrong "[[MIG] CRM: Migration to 17.0"

2024-11-29 07:38 UTC, hbrunn requested changes
@acpMicrocom I haven't seen followup on this PR lately, so I'll implement my comments in a new PR

2024-11-29 07:38 UTC, hbrunn commented on openupgrade_scripts/scripts/stock/17.0.1.1/upgrade_analysis_work.txt
> +# NOTHING TO DO
this is done in pre-migration where you transform `stock.scrap#move_id`

2024-11-29 07:38 UTC, hbrunn commented on openupgrade_scripts/scripts/stock/17.0.1.1/post-migration.py
> +# Copyright 2024 Viindoo Technology Joint Stock Company (Viindoo)
your copyright notices look wrong

2024-11-29 07:38 UTC, hbrunn commented on openupgrade_scripts/scripts/stock/17.0.1.1/pre-migration.py
> +    ("stock.move.line", "stock_move_line", "qty_done", "quantity"),
it's more complex than that. as this field now as well counts what is done and what it reserved, you need to add reserved_qty if qty_done was 0 or the move's state isn't done (depends a bit on how users used v16).

I suggest to copy the column instead of renaming to allow subsequent code make its own choices here

2024-11-29 07:38 UTC, hbrunn commented on openupgrade_scripts/scripts/stock/17.0.1.1/upgrade_analysis_work.txt
> +stock        / stock.move.line          / reserved_qty (float)          : DEL
see above

2024-11-29 07:38 UTC, hbrunn commented on openupgrade_scripts/scripts/stock/17.0.1.1/upgrade_analysis_work.txt
> +stock        / stock.picking            / return_ids (one2many)         : NEW relation: stock.picking
those we'll need to reconstruct from stock.move#origin_returned_move_id

2024-11-29 07:38 UTC, hbrunn commented on openupgrade_scripts/scripts/stock/17.0.1.1/upgrade_analysis_work.txt
> +stock        / stock.picking.type       / default_location_return_id (many2one): NEW relation: stock.location
this can be calculated that from the warehouse's old return picking type's default location

2024-11-29 19:29 UTC, hbrunn commented
superseded by #4681

2024-11-29 19:29 UTC, closed without merging