[17.0][OU-ADD] iap: Nothing to do
OCA/OpenUpgrade pull request #4586
Opened 2024-10-16 18:47 UTC by acpMicrocom

2024-10-21 09:39 UTC, rvalyi approved these changes
OK for me. I would say, please just squash the 3 commits in 1.

2024-10-24 09:25 UTC, xtanuiha approved these changes

2024-10-24 19:33 UTC, legalsylvain commented
/ocabot migration iap

2024-10-25 07:12 UTC, legalsylvain requested changes
Lgtm. Except state of module

2024-10-25 07:12 UTC, legalsylvain commented on docsource/modules160-170.rst
> +| iap                                               | Done                 |                                                 |
```suggestion
| iap                                               | Nothing to do        |                                                 |
```

2024-12-12 13:07 UTC, remi-filament commented
Hi @legalsylvain thanks for taking over this PR can you please close this PR and update migration issue with #4689 merged ?

2024-12-12 13:57 UTC, closed without merging