[OU-ADD] payment_custom: Migration to 17.0
OCA/OpenUpgrade pull request #4592
Opened 2024-10-18 09:57 UTC by remi-filament

2024-10-24 19:37 UTC, legalsylvain commented
/ocabot migration payment_custom

2025-02-25 15:16 UTC, carlos-lopez-tecnativa requested changes
Code review
TT49316

2025-02-25 15:16 UTC, carlos-lopez-tecnativa commented on openupgrade_scripts/scripts/payment_custom/17.0.2.0/pre-migration.py
> +    )
Why this change?
This constraint is present in V17:
https://github.com/odoo/odoo/blob/3c6a4aa06e22a6e2f6360790cf54380898915311/addons/payment_custom/models/payment_provider.py#L12-L16
And it is identical to V16:
https://github.com/odoo/odoo/blob/827ef9c0431e788cc4666fa635d705957db9d9f9/addons/payment_custom/models/payment_provider.py#L10-L14

2025-02-26 08:40 UTC, remi-filament commented on openupgrade_scripts/scripts/payment_custom/17.0.2.0/pre-migration.py
> +    )
Thanks for spotting that one, the constraint was detected as removed in previous analysis file (https://github.com/OCA/OpenUpgrade/commit/9bde91fbf9356f10077870e815292d8083e43f8c#diff-3cdf2dd014f579adff24b04f9b73b01993bd64a2994126c49adb566a23254901).
I should remove that !

2025-02-26 12:07 UTC, carlos-lopez-tecnativa commented
This PR causes a conflict with the CI:
https://github.com/odoo/odoo/pull/197886

@hbrunn could you please take a look?

2025-02-26 12:58 UTC, pedrobaeza commented
@StefanRijnhart @hbrunn @legalsylvain @MiquelRForgeFlow maybe we shouldn't execute Odoo "official" scripts (those with not fully qualified version) in OpenUpgrade? Other scripts done by Odoo in `l10n_es` have been constantly crashing my migrations and I just disabled this on a fork for continuing the migration.

2025-03-03 11:29 UTC, MiquelRForgeFlow commented
please rebase

2025-03-03 13:49 UTC, MiquelRForgeFlow approved these changes

2025-03-03 13:50 UTC, MiquelRForgeFlow commented
/ocabot merge nobump

2025-03-03 13:57 UTC, merged