[17.0][OU-IMP] new analysis (december 2024)
OCA/OpenUpgrade pull request #4697
Opened 2024-12-12 10:42 UTC by MiquelRForgeFlow

It hasn't changed much, as the last one was done on October (https://github.com/OCA/OpenUpgrade/commit/9bde91fbf9356f10077870e815292d8083e43f8c).

I added `"sale_quotation_builder": "sale_pdf_quote_builder`" in apriori, because expectations. People having the old one expects having the new one after the migration, independently if the code has changed between the modules.

2024-12-16 07:31 UTC, hbrunn requested changes
I think the rename should go into another commit than the analysis

2024-12-16 07:31 UTC, hbrunn commented on openupgrade_scripts/scripts/base_import_module/17.0.1.0/upgrade_analysis_work.txt
what's up with this rename?

2024-12-16 10:00 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/base_import_module/17.0.1.0/upgrade_analysis_work.txt
It's an error from https://github.com/OCA/OpenUpgrade/commit/60f18195d9c9db8b620a2610cbc150a1aaae3312, that was put the file in the wrong folder.

2024-12-16 10:16 UTC, pedrobaeza commented on openupgrade_scripts/scripts/base_import_module/17.0.1.0/upgrade_analysis_work.txt
cc @legalsylvain please take care of these things being the coordinator.

2024-12-16 11:04 UTC, legalsylvain commented on openupgrade_scripts/scripts/base_import_module/17.0.1.0/upgrade_analysis_work.txt
Sorry. My bad.

2024-12-16 18:21 UTC, hbrunn commented
bu still I think the addition to apriori.py should go in its own commit

2024-12-17 19:03 UTC, hbrunn approved these changes

2024-12-18 18:06 UTC, MiquelRForgeFlow commented
/ocabot merge nobump

2024-12-18 18:10 UTC, merged