[17.0][OU-ADD] hr_holidays: Migration to 17.0
OCA/OpenUpgrade pull request #4702
Opened 2024-12-24 12:28 UTC by remi-filament

2024-12-31 15:38 UTC, legalsylvain commented
/ocabot migration hr_holidays

2025-01-06 08:32 UTC, Murtaza-SerpentCS commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/pre-migration.py
> +]
Remove unused code.

2025-01-06 08:32 UTC, Murtaza-SerpentCS commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/pre-migration.py
> +]
Remove unused code

2025-01-06 08:34 UTC, Murtaza-SerpentCS commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/post-migration.py
> +    allocations.write({"already_accrued": True})
Convert to Query.

2025-01-06 08:34 UTC, Murtaza-SerpentCS commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/noupdate_changes.xml
> +  -->
Remove unused code.

2025-01-06 10:25 UTC, remi-filament commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/noupdate_changes.xml
> +  -->
Here, I think it is better to keep these so that we see what we should not update.

2025-01-06 10:26 UTC, remi-filament commented
Done as per your comments, thanks for your review @Murtaza-SerpentCS

2025-01-06 11:18 UTC, Murtaza-SerpentCS commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/noupdate_changes.xml
> +  -->
I don't think it's useful.

2025-01-06 12:08 UTC, remi-filament commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/noupdate_changes.xml
> +  -->
IMO it is, and it actually what is usually done on other scripts as well, see for instannce : https://github.com/OCA/OpenUpgrade/blob/c31d4d644143b5339498ca1215727842fa866de5/openupgrade_scripts/scripts/account/16.0.1.2/noupdate_changes.xml#L9-L30
The use case where it is useful is for when we run analysis again, (like it was done with https://github.com/OCA/OpenUpgrade/pull/4697) by keeping the comments, we know that these data were commented out willingly, and it was not new data which was added after last analysis or data which was forgotten.

2025-03-06 14:41 UTC, carlos-lopez-tecnativa requested changes
@remi-filament  could you please rebase the branch?

2025-03-06 18:01 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/upgrade_analysis_work.txt
> +# DONE pre-migration: rename model
could you add this in apriori file too?

2025-03-06 21:19 UTC, remi-filament commented
@carlos-lopez-tecnativa @MiquelRForgeFlow thanks for your review, rebase done and apriori updated.

2025-03-07 18:48 UTC, carlos-lopez-tecnativa requested changes
Tested and working, but I think we need to adjust some SQL to maintain the current behavior in V16. Please let me know if you have any doubts.
TT49870
cc: @pedrobaeza

2025-03-07 18:48 UTC, carlos-lopez-tecnativa commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/upgrade_analysis_work.txt
> +hr_holidays  / hr.leave                 / company_id (many2one)         : NEW relation: res.company, isfunction: function, stored
I think using SQL instead of ORM to fill this field is a good option, especially for databases with a large number of records. What do you think?

2025-03-07 18:48 UTC, carlos-lopez-tecnativa commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/pre-migration.py
> +        WHERE level.accrual_plan_id = plan.id;
I think that if any level is set to `True`, then the new field in the plan must also be set to `True`.

In the current script, the field in the plan is set to `False` because there is no defined order—it takes the first, last, or a random level?.
V16, Set to `True` on the second level
![image](https://github.com/user-attachments/assets/9975f607-641b-47a5-bbf6-7939f0b79d55)

V17
![image](https://github.com/user-attachments/assets/92725fe6-3465-465a-b3ca-d3e25d3bfb3a)

```suggestion
        UPDATE hr_leave_accrual_plan plan
        SET is_based_on_worked_time = subquery.max_value
        FROM (
            SELECT accrual_plan_id, MAX(is_based_on_worked_time::INT) AS max_value
            FROM hr_leave_accrual_level
            GROUP BY accrual_plan_id
        ) subquery
        WHERE subquery.accrual_plan_id = plan.id;
```

2025-03-07 18:48 UTC, carlos-lopez-tecnativa commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/pre-migration.py
> +        WHERE action_with_unused_accruals = 'postponed';
I think setting this field to `all` always is incorrect; it must depend on the `maximum_leave` field.
Otherwise, it can never be applied according to [this code](https://github.com/odoo/odoo/blob/7bf18616e4ae39c5e712339cfd560b57018a93de/addons/hr_holidays/models/hr_leave_allocation.py#L521-L524
)

V16
![image](https://github.com/user-attachments/assets/d87bd494-bdfa-495f-894c-b6175a9d45d4)
V17
![image](https://github.com/user-attachments/assets/8ae4d317-cd22-4986-b394-436d6819db66)

V17 expected behavior
![image](https://github.com/user-attachments/assets/39430ff9-6f42-47fc-bae1-a6213eb5fc44)

```suggestion
        UPDATE hr_leave_accrual_level
        SET action_with_unused_accruals = CASE 
                WHEN maximum_leave > 0 THEN 'maximum' 
                ELSE 'all' 
                END
        WHERE action_with_unused_accruals = 'postponed';
```

2025-03-11 12:51 UTC, carlos-lopez-tecnativa commented
ping @remi-filament

2025-03-11 14:33 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/pre-migration.py
> +    )
```suggestion
    openupgrade.logged_query(
        cr,
        """UPDATE hr_leave AS leave
        SET company_id = CASE
            WHEN employee_company_id IS NOT NULL THEN employee_company_id
            WHEN mode_company_id IS NOT NULL THEN mode_company_id
            ELSE NULL
            END
        WHERE leave.company_id IS NULL""",
    )
    openupgrade.logged_query(
        cr,
        """UPDATE hr_leave AS leave
        SET company_id = d.company_id
        FROM hr_department AS d
        WHERE leave.company_id IS NULL AND leave.department_id = d.id""",
    )
```

2025-03-11 14:41 UTC, remi-filament commented
Thanks @carlos-lopez-tecnativa and @MiquelRForgeFlow I implemented the changes as per your review !

2025-03-11 16:30 UTC, carlos-lopez-tecnativa requested changes
Just a minor change, and I think it's ready to merge.

2025-03-11 16:30 UTC, carlos-lopez-tecnativa commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/pre-migration.py
> +                WHEN maximum_leave > 0 THEN 'maximum'
Please fine-tune this to avoid considering it if the value is zero.
```suggestion
                WHEN maximum_leave > 0 AND postpone_max_days > 0  THEN 'maximum'
```
V16
![image](https://github.com/user-attachments/assets/7de24d09-a697-4e9c-89bb-c9faa1dba323)

V17: If the value is zero, it is better to keep the default value.
![image](https://github.com/user-attachments/assets/ff96cbf6-028f-4796-86d4-010a8baf6d8f)

2025-03-11 18:55 UTC, carlos-lopez-tecnativa approved these changes
LGTM

2025-03-12 09:27 UTC, MiquelRForgeFlow commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/upgrade_analysis_work.txt
> +# NOTHING TO DO: new field, default = active
please, do like `_pre_create_account_report_active` in pre-migration of `account`.

2025-03-12 20:52 UTC, remi-filament commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/upgrade_analysis_work.txt
> +# NOTHING TO DO: new field, default = active
Done, what is the rationale to create columns in SQL instead of letting Odoo do it, is it so much performance gain ?
Should we do this for all new fields with default value ? (there are lots of them on hr.leave.accrual.plan : accrued_gain_time, added_value_type, carryover_date, carryover_day, carryover_month).

2025-03-12 21:06 UTC, carlos-lopez-tecnativa commented on openupgrade_scripts/scripts/hr_holidays/17.0.1.6/upgrade_analysis_work.txt
> +# NOTHING TO DO: new field, default = active
My logic is that if a model is transactional (with many records, such as `account.move`, `account.move.line`, `stock.move`, `stock.move.line`, `sale.order`, `sale.order.line`, etc.), it should be handled using SQL instead of the ORM. However, if the model is a master record (with only a few records, typically settings), then using the ORM is sufficient.

It would be great to hear the logic from others, such as @pedrobaeza @MiquelRForgeFlow, to take different perspectives into account.

2025-03-13 11:41 UTC, MiquelRForgeFlow approved these changes

2025-03-13 11:41 UTC, MiquelRForgeFlow commented
/ocabot merge nobump

2025-03-13 11:50 UTC, merged