[MIG] procurement module migration scripts
OCA/OpenUpgrade pull request #672
Opened 2016-11-24 10:27 UTC by cubells

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

 * completed analysys
 * added analysis_work file

2016-11-24 10:31 UTC, pedrobaeza commented on addons/procurement/migrations/9.0.1.0/openupgrade_analysis.txt
> +procurement  / procurement.order        / message_follower_ids (many2many)      : not a function anymore
Why have you changed this file?

2016-11-24 10:32 UTC, pedrobaeza commented
You have to update documentation in https://github.com/OCA/OpenUpgrade/blob/9.0/openerp/openupgrade/doc/source/modules80-90.rst

2016-11-24 12:02 UTC, cubells commented on addons/procurement/migrations/9.0.1.0/openupgrade_analysis.txt
> +procurement  / procurement.order        / message_follower_ids (many2many)      : not a function anymore
To add some analysis of fields/views that are missing in initial analysis.

2016-11-24 12:05 UTC, pedrobaeza commented on addons/procurement/migrations/9.0.1.0/openupgrade_analysis.txt
> +procurement  / procurement.order        / message_follower_ids (many2many)      : not a function anymore
Two things about this:

* Don't change lines although the indentation is not so good for not increasing the diff.
* Why they are not included? Maybe we should improve the analysis method. Anyway, don't include here that extra lines, but it _work file.

2016-11-24 23:18 UTC, pedrobaeza commented on addons/procurement/migrations/9.0.1.0/openupgrade_analysis_work.txt
> +procurement  / procurement.order        / product_uos (many2one)                : DEL relation: product.uom
If this dissapears, maybe now `product_uos` and `product_uos_qty` of the sales orders are put directly in `product_uom` and `product_uom_qty`. If so, then you should include a script for copying "uos" values (in pre-migration) to "uom" when "uos" is present. Please check the behavior in v8 and v9 when you put sales units and tell me back.

2016-11-25 14:43 UTC, cubells commented on addons/procurement/migrations/9.0.1.0/openupgrade_analysis_work.txt
> +procurement  / procurement.order        / product_uos (many2one)                : DEL relation: product.uom
Not.

product_uos and product_uos_qty dissapear:
https://github.com/OCA/OpenUpgrade/blob/9.0/addons/sale/sale.py#L557
and product_uom is setted with product_uom and product_uom_qty.


I'm right?

2016-11-25 16:08 UTC, pedrobaeza commented on addons/procurement/migrations/9.0.1.0/openupgrade_analysis_work.txt
> +procurement  / procurement.order        / product_uos (many2one)                : DEL relation: product.uom
OK, correct, then nothing to do on this.

2016-11-25 16:09 UTC, pedrobaeza requested changes

2016-11-25 16:09 UTC, pedrobaeza commented on openerp/openupgrade/doc/source/modules80-90.rst
> +|procurement                        | Done                              |
s/Done/Nothing to do

2016-11-25 16:11 UTC, pedrobaeza approved these changes

2016-11-25 16:21 UTC, merged