[MIG] survey module migration script
OCA/OpenUpgrade pull request #674
Opened 2016-11-24 16:19 UTC by cubells

* Created openupgrade_analysis_work.txt
 * Updated module coverage document

2016-11-24 16:20 UTC, cubells commented
@Tecnativa

2016-11-24 23:23 UTC, pedrobaeza requested changes
I have found that there's a change in noupdate data:

```
<?xml version='1.0' encoding='utf-8'?>
<openerp>
  <data>
    <record id="base.group_survey_manager" model="res.groups"><field name="name">Manager</field>
            <field name="category_id" ref="base.module_category_survey"/>
            </record>
    <record id="base.group_survey_user" model="res.groups"><field name="name">User</field>
            <field name="category_id" ref="base.module_category_survey"/>
        </record>
  </data>
</openerp>
```

Take a look on this to see how to load it: https://github.com/OCA/OpenUpgrade/blob/71c6abdd40561c22fdaf03fb3cfbca5508231f9a/addons/hr_contract/migrations/9.0.1.0/post-migration.py#L9

2016-11-25 16:06 UTC, pedrobaeza requested changes

2016-11-25 16:06 UTC, pedrobaeza commented on openerp/openupgrade/doc/source/modules80-90.rst
> +|survey                             | Nothing to do                     |
s/Nothing to do/Done

2016-11-25 18:09 UTC, pedrobaeza approved these changes

2016-11-25 18:09 UTC, merged