[MIG] website_sale module migration script
OCA/OpenUpgrade pull request #676
Opened 2016-11-24 17:51 UTC by cubells

* Created openupgrade_analysis_work.txt
 * Updated module coverage document

@Tecnativa

2016-11-24 23:40 UTC, pedrobaeza commented on addons/website_sale/migrations/9.0.1.0/openupgrade_analysis_work.txt
> +# Nothing to do
We can try to deduce this looking for a sales order that comes from website from this partner.

2016-11-25 15:24 UTC, cubells commented on addons/website_sale/migrations/9.0.1.0/openupgrade_analysis_work.txt
> +# Nothing to do
A possible solution.

2016-11-25 15:59 UTC, pedrobaeza requested changes

2016-11-25 15:59 UTC, pedrobaeza commented on openerp/openupgrade/doc/source/modules80-90.rst
> +|website_sale                       | Nothing to do                     |
This should be `Done`

2016-11-25 15:59 UTC, pedrobaeza commented on addons/website_sale/migrations/9.0.1.0/post-migration.py
> +    partners = env['res.partner'].search([])
This is going to be awfully slow. You can use an SQL to make this:
```
UPDATE res_partner rp
SET last_website_so_id = so.id
FROM sale_order so
WHERE so.id = (
   SELECT max(id) FROM sale_order
   WHERE partner_id = rp.id
)
AND rp.last_website_so_id IS NULL;
```
Note that `website_order_line` is a one2many field that behaves the same of normal order_line (so all sales orders are website applicable).

2016-11-25 16:43 UTC, cubells commented on addons/website_sale/migrations/9.0.1.0/post-migration.py
> +    partners = env['res.partner'].search([])
But how can I know which sales are normal sale and which sales are web sales?

2016-11-25 16:47 UTC, cubells commented on addons/website_sale/migrations/9.0.1.0/post-migration.py
> +    partners = env['res.partner'].search([])
Ok. I read your message now.

2016-11-25 17:51 UTC, pedrobaeza approved these changes

2016-11-25 17:51 UTC, merged