[MIG] hr_recruitment module migration script
OCA/OpenUpgrade pull request #682
Opened 2016-11-28 09:04 UTC by cubells

* Added analysis files
 * Created pre and post files

2016-11-28 13:28 UTC, legalsylvain commented
Hi  @cubells Thanks for your work. Could you add in your PR the change of the module coverage file. (set to 'Done' hr_recrutment line.)
https://github.com/OCA/OpenUpgrade/blob/9.0/openerp/openupgrade/doc/source/modules80-90.rst

kind regards.

2016-11-28 14:06 UTC, cubells commented
Done @legalsylvain

2016-11-29 01:15 UTC, pedrobaeza requested changes

2016-11-29 01:15 UTC, pedrobaeza commented on addons/hr_recruitment/migrations/9.0.1.0/openupgrade_analysis_work.txt
> +# Unable to calculate date form a integer --> Nothing to do
You should take field `create_date` and add this number of days to get the new date.

2016-11-29 01:15 UTC, pedrobaeza commented on addons/hr_recruitment/migrations/9.0.1.0/openupgrade_analysis_work.txt
> +# Nothing to do
You need to create an utm.source for each of the existing hr.recruitment.source, as now the object inherits (via delegation) of this object, and fill the corresponding field:
````
cr.execute('INSERT INTO utm_source ... RETURNING id')
new_id = cr.fetchone()
cr.execute('UPDATE hr_applicant SET source_id = %s WHERE id = %s', (new_id, old_id))
```

2016-11-29 21:29 UTC, pedrobaeza commented on addons/hr_recruitment/migrations/9.0.1.0/post-migration.py
> +            new_date += timedelta(days=applicant[2])
You must convert this again: `fields.Date.to_string(new_date)`

2016-11-29 21:30 UTC, pedrobaeza commented on addons/hr_recruitment/migrations/9.0.1.0/pre-migration.py
> +def migrate_applicant_source(cr):
You should do this on post-migration, as utm.source doesn't have yet the new structure.

2016-11-30 07:09 UTC, pedrobaeza commented on addons/hr_recruitment/migrations/9.0.1.0/post-migration.py
> +        [('4', '3'), ('3', '1'), ('2', '0'), ('1', '0')],
You must change the map_values order, as this is got iterating over values, so in your current map, you will replace `4` value by `3`, and next iteration, the existing `3` and the new `3` will be replaced by `1`. You must reverse the mapping.

And another thing, why there's no `2` in the new mapping?

2016-11-30 07:28 UTC, cubells commented on addons/hr_recruitment/migrations/9.0.1.0/post-migration.py
> +        [('4', '3'), ('3', '1'), ('2', '0'), ('1', '0')],
I do that mapping:
4 is excellent and is mapped to excellent.
3 is good and is mapped to good.
All the others are mapped to normal.
Very good is no mapped.

2016-11-30 07:32 UTC, pedrobaeza commented on addons/hr_recruitment/migrations/9.0.1.0/post-migration.py
> +        [('4', '3'), ('3', '1'), ('2', '0'), ('1', '0')],
But right now three of the old values map to the new 0 (0, 1 and 2). Is that correct?

2016-11-30 07:35 UTC, cubells commented on addons/hr_recruitment/migrations/9.0.1.0/post-migration.py
> +        [('4', '3'), ('3', '1'), ('2', '0'), ('1', '0')],
yes, It is.

Average, Below Average and Bad are mapped to Normal because there is not another similar value.

2016-11-30 07:39 UTC, pedrobaeza commented on addons/hr_recruitment/migrations/9.0.1.0/post-migration.py
> +            WHERE id = '%s'
You need to do this because you're not using psycopg capability to convert types. You have to do this:
```
WHERE id = %s
""", (new_date, applicant[0]))
```
This will also prevent SQL injection possibilities: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#no-sql-injection

2016-11-30 07:42 UTC, cubells commented on addons/hr_recruitment/migrations/9.0.1.0/post-migration.py
> +            WHERE id = '%s'
It's true.
thanks @pedrobaeza

2016-11-30 14:33 UTC, pedrobaeza commented on addons/hr_recruitment/migrations/9.0.1.0/post-migration.py
> +                   "FROM hr_recruitment_source "
You have to rename table to avoid the removal of the significant fields in the update process

2016-12-06 22:35 UTC, susport commented on addons/hr_recruitment/migrations/9.0.1.0/noupdate_changes.xml
> +<openerp>
Remove labels openerp data by odoo in v9.0

2016-12-06 22:37 UTC, pedrobaeza commented on addons/hr_recruitment/migrations/9.0.1.0/noupdate_changes.xml
> +<openerp>
This is an automatic file generated by https://github.com/OCA/OpenUpgrade/blob/9.0/scripts/compare_noupdate_xml_records.py, so we can leave it as is for this version and change the script for next one.

2016-12-06 23:57 UTC, pedrobaeza commented on addons/hr_recruitment/migrations/9.0.1.0/pre-migration.py
> +    openupgrade.rename_tables(cr, table_renames)
Line at the end

2016-12-06 23:57 UTC, pedrobaeza commented on addons/hr_recruitment/migrations/9.0.1.0/post-migration.py
> +                   "FROM hr_recruitment_source "
Here you have to access to the migrated table name, not the new one.

2016-12-07 12:29 UTC, pedrobaeza approved these changes

2016-12-07 12:29 UTC, merged