[FIX] precompute sheet_id in analytic lines
OCA/OpenUpgrade pull request #767
Opened 2017-02-18 01:33 UTC by jbeficent

This PR will precompute the field sheet_id in analytic lines, to avoid the recomputation made by odoo, that turns out to produce errors.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2017-02-18 01:56 UTC, hbrunn requested changes
I'd suggest using the mechanism @NL66278 employs in https://github.com/OCA/OpenUpgrade/pull/663/files#diff-050c291be549d31c2482669f8281e619R169 - this way, you don't miss creating the index on `sheet` id for example: https://github.com/OCA/OCB/blob/9.0/addons/hr_timesheet_sheet/hr_timesheet_sheet.py#L331

2017-02-20 10:36 UTC, jbeficent commented
@hbrunn Thanks. But then the method `_openupgrade_recompute_fields_blacklist` should be proposed in a separate PR, not associated with the PR specific to accounting, right? cc @NL66278

2017-02-20 10:45 UTC, NL66278 commented
@jbeficent @hbrunn There actually is a seprate PR for this: https://github.com/OCA/OpenUpgrade/pull/735

I found an issue with the above mentioned PR that blacklists are not always removed automatically. That is why in the reconciliation PR I removed them manually. As I found no obvious way to register globally what blacklists have registered, I got stuck at how to remove them automatically. That is why this PR is still WIP.

2017-02-20 17:42 UTC, jbeficent commented
@hbrunn @NL66278 As it seems that the PR is not concluded, why not manually creating the index, same as https://github.com/odoo/odoo/blob/9.0/openerp/models.py#L2616?

2017-02-20 17:43 UTC, hbrunn approved these changes

2017-02-20 17:43 UTC, hbrunn commented
fine with me for now

2017-02-20 17:46 UTC, NL66278 commented
:+1:  If index is also created as already suggested by @jbeficent

2017-02-21 13:32 UTC, jbeficent commented
Index is now correctly created:

v8:
![image](https://cloud.githubusercontent.com/assets/7683926/23166856/8f715e5a-f842-11e6-86e2-216c4aa4c621.png)


v9:
![image](https://cloud.githubusercontent.com/assets/7683926/23166846/7d5e84d6-f842-11e6-9b9d-79d3983bb9ca.png)

@hbrunn  can you merge?

2017-02-21 13:36 UTC, merged