Nothing to do on these WEB_X modules
OCA/OpenUpgrade pull request #799
Opened 2017-05-01 12:17 UTC by gfcapalbo

Description of the issue/feature this PR addresses:
Tagging web_calendar , web_diagram  , web_kanban   ,web_kanban_gauge  as  'nothing to do'

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2017-05-01 15:15 UTC, pedrobaeza requested changes
I have checked folders and run the script for looking for noupdate changes. One a little comment that I think it's important.

2017-05-01 15:15 UTC, pedrobaeza commented on odoo/openupgrade/doc/source/modules90-100.rst
> +|web_diagram                        | Nothing to do                     |
As this module contains a migrations folder, it's convenient to include the openupgrade_analysis_work.txt file indicating that there's nothing to do. This way, looking at the folder structure without checking this documentation, you can see if the module has been analyzed.

2017-05-02 11:12 UTC, pedrobaeza approved these changes
Well, this is normally performed copying the analysis file, and adding on the corresponding sections "Nothing to do" for reviewers to check if it's that way, but it's very simple, so I approve it.

Travis error is unrelated and should be fixed when migrating `crm`.

2017-05-02 12:02 UTC, gfcapalbo commented
Fixed the work comments according to usual standards and rebased.

2017-05-02 12:09 UTC, pedrobaeza commented
There's something strange in the rebase. Please check.

2017-05-02 12:20 UTC, gfcapalbo commented
conflict solved

2017-05-05 08:48 UTC, pedrobaeza commented
I still see a lot of commit that don't belong here

2017-05-09 10:05 UTC, hbrunn commented
this branch still needs cleaning up

2017-05-10 11:37 UTC, gfcapalbo commented on odoo/openupgrade/doc/source/modules90-100.rst
> +|web_diagram                        | Nothing to do                     |
done

2017-05-10 11:40 UTC, gfcapalbo commented
cannot find anything wrong except for the travis CRM, cleaned up from a fresh OCA 10.0 and cherry picked my small commit.

2017-05-10 11:49 UTC, hbrunn commented
you didn't use a pristine 10.0 branch, but some other one that contains the extra commits @pedrobaeza and me are talking about

2017-05-11 07:41 UTC, merged