[ADD][10.0] account_asset migration script
OCA/OpenUpgrade pull request #839
Opened 2017-05-23 08:27 UTC by cubells

cc @Tecnativa

2017-05-23 09:41 UTC, pedrobaeza approved these changes

2017-05-23 09:42 UTC, pedrobaeza requested changes

2017-05-23 09:42 UTC, pedrobaeza commented on addons/account_asset/migrations/10.0.1.0/pre-migration.py
> +def migrate(cr, version):
This is env now by default and you have to use `env.cr` then

2017-05-23 10:35 UTC, cubells commented on addons/account_asset/migrations/10.0.1.0/pre-migration.py
> +def migrate(cr, version):
Do you prefer to use use_env=False or to use use_env=True?

2017-05-23 10:36 UTC, pedrobaeza commented on addons/account_asset/migrations/10.0.1.0/pre-migration.py
> +def migrate(cr, version):
I prefer the standard (which is use_env=True)

2017-05-25 00:06 UTC, pedrobaeza commented on addons/account_asset/migrations/10.0.1.0/pre-migration.py
> +@openupgrade.migrate(use_env=True)
No need to put `use_env=True`, as it's the default in v10, but it's not so important.

2017-05-25 00:06 UTC, pedrobaeza approved these changes

2017-05-25 00:07 UTC, merged