[10.0][MIG] sale
OCA/OpenUpgrade pull request #851
Opened 2017-05-29 14:57 UTC by rruebner

FYI: I also updated the analysis text file for the sale module here. The rest of the analysis text files were updated in #850.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2017-05-29 15:04 UTC, cubells requested changes
Typo

2017-05-29 15:04 UTC, cubells commented on odoo/openupgrade/doc/source/modules90-100.rst
> +|sale                               | Done                                  |
Typo: there are 4 extra spaces. :)

2017-05-30 00:12 UTC, pedrobaeza requested changes

2017-05-30 00:12 UTC, pedrobaeza commented on addons/sale/migrations/10.0.1.0/openupgrade_analysis_work.txt
>  # NOTHING TO DO
This is not correct, as sale now integrates sale_layout module. You need to run update_module_names with the merge option activated and check if there's any change on data model

2017-05-30 00:12 UTC, pedrobaeza commented on addons/sale/migrations/10.0.1.0/openupgrade_analysis_work.txt
> +# NOTHING TO DO
Please check it if warning module was installed on v9 and rescue values from it.

2017-05-30 00:12 UTC, pedrobaeza commented on addons/sale/migrations/10.0.1.0/post-migration.py
> +    cr.execute("""
You can use openupgradelib map_values function for readibility and extra log.

2017-05-30 12:26 UTC, rruebner commented
@pedrobaeza I updated the migration parts according to your mentioned points. In addition I rechecked all parts again and added some more migration parts.

2017-05-30 14:35 UTC, pedrobaeza requested changes
Check if you need to rename the security groups

2017-05-30 14:35 UTC, pedrobaeza commented on addons/sale/migrations/10.0.1.0/pre-migration.py
> +    we would use openupgrade.update_module_names their might be problems when
s/their/there

2017-05-30 14:35 UTC, pedrobaeza commented on addons/sale/migrations/10.0.1.0/pre-migration.py
> +    first use openupgrade.update_module_names in sale module and than again in
s/use/using

2017-05-30 14:35 UTC, pedrobaeza commented on addons/sale/migrations/10.0.1.0/pre-migration.py
> +    first use openupgrade.update_module_names in sale module and than again in
s/than/then

2017-05-31 09:28 UTC, rruebner commented
@pedrobaeza I fixed the mentioned typos and rechecked security group changes. AFAICS there is no extra renaming needed (possible renaming is covered by update_module_names calls).
I also checked for noupdate=1 records and everything was fine.

2017-06-07 13:46 UTC, MiquelRForgeFlow approved these changes
LGTM! :+1:

2017-06-07 15:21 UTC, pedrobaeza commented
Thanks for the changes, Robert.

If you don't mind, I'm going to keep the PRs unmerged until we get a green branch for not adding more complexity to the pipe and possible side effects.

2017-06-12 10:32 UTC, mreficent commented
Please, rebase the PR (and squash minor commits) ☺️

2017-06-15 16:02 UTC, MiquelRForgeFlow requested changes
A new line appeared https://github.com/OCA/OpenUpgrade/pull/917/files#diff-1c07737aeb217d5e147f8fa6d1204414R5, and it should be attended in an easy post-migration script.

2017-06-21 10:26 UTC, omar7r commented on addons/sale/migrations/10.0.1.0/pre-migration.py
> +column_renames = {
If you don't have installed "sale_layout" module, columns renaming and the models renaming fails, maybe, you have to check if this module is installed to execute this two functions

2017-06-29 00:13 UTC, pedrobaeza commented
This fails due to TRAVIS_COMMIT, but I have checked it and fix it, so I merge.

2017-06-29 00:13 UTC, pedrobaeza approved these changes

2017-06-29 00:13 UTC, merged