[10.0][MIG] sale_stock
OCA/OpenUpgrade pull request #853
Opened 2017-05-29 16:05 UTC by reinka

This PR adds the migration scripts to v10 for the sale_stock module.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2017-05-29 23:49 UTC, pedrobaeza requested changes
Add in the documentation (https://github.com/OCA/OpenUpgrade/blob/10.0/odoo/openupgrade/doc/source/modules90-100.rst) the "Done" word for this module.

2017-05-29 23:49 UTC, pedrobaeza commented on addons/sale_stock/migrations/10.0.1.0/openupgrade_analysis_work.txt
> +sale_stock   / stock.move               / to_refund_so (boolean)        : NEW
Please marked as default this field, as if you come from v9, you expect that all the already made moves are refundable.

2017-05-30 11:24 UTC, reinka commented on addons/sale_stock/migrations/10.0.1.0/openupgrade_analysis_work.txt
> +sale_stock   / stock.move               / to_refund_so (boolean)        : NEW
@pedrobaeza Update according to your request

2017-05-30 11:41 UTC, pedrobaeza approved these changes

2017-05-30 11:41 UTC, merged

2017-05-30 12:36 UTC, jholze commented
👍

2017-05-31 07:07 UTC, StefanRijnhart commented
@pedrobaeza please don't merge modules of which the dependencies have not yet been merged because it makes it impossible for us to get Travis green.