[9.0][Upd] module coverage list
OCA/OpenUpgrade pull request #913
Opened 2017-06-13 10:02 UTC by mreficent

I found very useful in v10 the ![image](https://user-images.githubusercontent.com/25005517/27077188-882ee118-502f-11e7-8a79-733760550868.png) tag to know which modules are missing. So I thought to apply the same in v9.

The changes in this PR are not an exhaustive list of missing modules but it's a first approach.

2017-06-13 10:53 UTC, pedrobaeza commented
Please complete the list then, or we will think that it's complete.

2017-06-13 14:48 UTC, mreficent commented
The list is now exhaustively completed 💪😎

2017-06-18 15:15 UTC, pedrobaeza requested changes

2017-06-18 15:15 UTC, pedrobaeza commented on openerp/openupgrade/doc/source/modules80-90.rst
> +| |del| account_check_writing            | Renamed [#account_check_writing]_ |
Shouldn't this be account_check_printing?

2017-06-18 15:15 UTC, pedrobaeza commented on openerp/openupgrade/doc/source/modules80-90.rst
> +| |del| account_bank_statement_extensions|                                   |
As you are changing the entire file, better to give some more room to the columns, specially the second column that can contain references to renamings

2017-06-18 15:15 UTC, pedrobaeza commented on openerp/openupgrade/doc/source/modules80-90.rst
> +| |del| account_analytic_plans           |                                   |
There's an equivalent module and OpenUpgrade renames it to it in https://github.com/OCA/account-analytic/tree/9.0/account_analytic_distribution

2017-06-18 15:15 UTC, pedrobaeza commented on openerp/openupgrade/doc/source/modules80-90.rst
> +|l10n_sg                                 |
Equivalent module and renamed in OU: https://github.com/OCA/account-analytic/tree/9.0/purchase_analytic_distribution

2017-06-18 15:15 UTC, pedrobaeza commented on openerp/openupgrade/doc/source/modules80-90.rst
> +|l10n_sg                                 |
Equivalent module and renamed in OU in https://github.com/OCA/account-analytic/tree/9.0/sale_analytic_distribution

2017-06-19 08:34 UTC, mreficent commented on openerp/openupgrade/doc/source/modules80-90.rst
> +| |del| account_check_writing            | Renamed [#account_check_writing]_ |
writing vs printing?  😏

2017-06-19 08:35 UTC, pedrobaeza commented on openerp/openupgrade/doc/source/modules80-90.rst
> +| |del| account_check_writing            | Renamed [#account_check_writing]_ |
Yes, I see that this a foot note, but at first sight I saw renamed and the same name and thought that there was an error.

2017-06-19 08:38 UTC, mreficent commented on openerp/openupgrade/doc/source/modules80-90.rst
> +| |del| account_bank_statement_extensions|                                   |
Who encounters a problem with the width of the second column is who should change the width, not me 😒

2017-06-19 08:43 UTC, pedrobaeza commented on openerp/openupgrade/doc/source/modules80-90.rst
> +| |del| account_bank_statement_extensions|                                   |
Yeah, but this means again another full diff. That's why I asking you this favor for not having such big diffs each time.

2017-06-19 08:54 UTC, mreficent commented on openerp/openupgrade/doc/source/modules80-90.rst
> +| |del| account_bank_statement_extensions|                                   |
Ok, I encountered the problem 😂

2017-06-19 09:14 UTC, mreficent commented
It's ready @pedrobaeza

2017-06-19 09:30 UTC, mreficent commented on openerp/openupgrade/doc/source/modules80-90.rst
> +| |del| account_bank_statement_extensions|                                   |
The spacing in the second column is done :+1:

2017-06-19 10:15 UTC, pedrobaeza approved these changes
Thank you very much. Now the documentation shines much more brighter :wink:

2017-06-19 10:16 UTC, pedrobaeza commented
Travis error is as always due to incorrect `TRAVIS_COMMIT` environment variable, so it's safe to merge.

2017-06-19 10:16 UTC, merged