[ADD] sale_documents_comments renamed
OCA/OpenUpgrade pull request #976
Opened 2017-07-26 12:02 UTC by chienandalu

As requested in https://github.com/OCA/sale-workflow/pull/509#issuecomment-317485138

cc @Tecnativa

2017-07-26 13:40 UTC, MiquelRForgeFlow requested changes

2017-07-26 13:40 UTC, mreficent commented on openerp/addons/openupgrade_records/lib/apriori.py
> +    'sale_documents_comments': 'sale_comment_propagation',
the module https://github.com/OCA/sale-workflow/pull/509 is still named `sale_comment_propagation`, see last commit

2017-07-26 13:46 UTC, mreficent commented
I think this PR should be closed, at least while the referenced PR is named as it is now

2017-07-26 15:12 UTC, pedrobaeza commented on openerp/addons/openupgrade_records/lib/apriori.py
> +    'sale_documents_comments': 'sale_comment_propagation',
We know that. This is for ensuring the migration path from odoomrp-wip module to OCA. If you have already 8.0 OCA module, this is harmless (well, not yet).

2017-07-26 15:13 UTC, pedrobaeza requested changes
@chienandalu, you have to include the renaming in the base module where update_module_names is called with merge_modules=True option, as you can have both modules (old and new) in your module list.

2017-07-26 15:15 UTC, pedrobaeza commented on openerp/addons/openupgrade_records/lib/apriori.py
> +    'sale_documents_comments': 'sale_comment_propagation',
It has been already done in other odoomrp-wip modules. See https://github.com/OCA/OpenUpgrade/blob/3243e327e903bd0b24db41f9cf922bc2cdb7fc20/openerp/addons/openupgrade_records/lib/apriori.py#L30

2017-07-26 15:15 UTC, mreficent commented on openerp/addons/openupgrade_records/lib/apriori.py
> +    'sale_documents_comments': 'sale_comment_propagation',
Oh, fine!

2017-07-27 17:58 UTC, chienandalu commented
Done @pedrobaeza

2017-07-28 00:54 UTC, pedrobaeza commented
But you haven't removed it from apriori.py...

2017-07-28 07:14 UTC, chienandalu commented
Sure, @pedrobaeza... :sweat_smile:  It's done

2017-07-28 07:32 UTC, MiquelRForgeFlow approved these changes

2017-07-28 07:39 UTC, mreficent commented
@chienandalu, why you put the depends in the head comment? It doesn't depend at all.

2017-07-28 07:47 UTC, chienandalu commented
@mreficent Yes, now it doesn't. Changed.

2017-07-28 07:47 UTC, pedrobaeza approved these changes

2017-07-28 07:47 UTC, merged

2017-07-28 07:48 UTC, pedrobaeza commented
It seems Travis has fixed its problem referencing $TRAVIS_COMMIT with force pushed PRs...